Repository OCA/bank-payment, pull requests merged in 2019-03, with the labels that each got.

#548 [FIX] account_payment_order: Fix journal domain
  account_payment_order/models/account_payment_order.py
  account_payment_order/views/account_payment_order.xml
Labels: approved, needs review

#558 [12.0] [REF] Account Banking Pain Base: constraint on BIC
  account_banking_pain_base/models/__init__.py
  account_banking_pain_base/models/res_bank.py
Labels: approved, needs review

#566 [12.0] [REF] Banking Mandate: searches with sudo in constraint
  account_banking_mandate/models/account_banking_mandate.py
Labels: approved, needs review

#538 [12.0] [REF] Payment Order: better performance of draft2open method
  account_payment_order/models/account_payment_order.py
Labels: approved, needs review, ready to merge

#567 [12.0] [ADD] Payment Order: only payment order option on payment methods
  account_payment_order/__manifest__.py
  account_payment_order/models/__init__.py
  account_payment_order/models/account_journal.py
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_method.py
  account_payment_order/tests/__init__.py
  account_payment_order/tests/test_account_payment.py
  account_payment_order/views/account_payment_method.xml
Labels: approved, needs review, ready to merge

#563 [12.0] [REF] Banking Mandate: move payment lines list in shortcut button
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/tests/test_invoice_mandate.py
  account_banking_mandate/views/account_banking_mandate_view.xml
Labels: approved, needs review

#570 [10.0] account_banking_pain_base: Allow override of address block
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/models/account_payment_order.py
Labels: approved

#572 [12.0][FIX] account_banking_pain_base bic constrains
  account_banking_pain_base/models/res_bank.py
Labels: approved
