Repository OCA/bank-payment, pull requests merged in 2019-11, with the labels that each got.

#647 [FIX] account_banking_sepa_direct_debit: UserError instead of Warning
  account_banking_sepa_direct_debit/models/account_payment_order.py
Labels: approved, merged 🎉

#652 [FIX] account_payment_purchase: Do not warn if no purchase
  account_payment_purchase/models/account_invoice.py
Labels: approved

#653 [FIX] account_banking_sepa_direct_debit: Fix report mandate
  account_banking_sepa_direct_debit/views/report_sepa_direct_debit_mandate.xml
Labels: approved

#655 [FIX] account_payment_mode: Always set company bank account in customer
  account_payment_mode/models/__init__.py
  account_payment_mode/models/account_invoice.py
Labels: approved, ready to merge
