Repository OCA/bank-payment, pull requests merged in 2019-04, with the labels that each got.

#574 [12.0][MIG] account_payment_order_return
  account_payment_order_return/README.rst
  account_payment_order_return/__init__.py
  account_payment_order_return/__manifest__.py
  account_payment_order_return/i18n/account_payment_order_return.pot
  account_payment_order_return/i18n/ca.po
  account_payment_order_return/i18n/de.po
  account_payment_order_return/i18n/es.po
  account_payment_order_return/i18n/fr.po
  account_payment_order_return/readme/CONTRIBUTORS.rst
  account_payment_order_return/readme/DESCRIPTION.rst
  account_payment_order_return/readme/INSTALL.rst
  account_payment_order_return/readme/USAGE.rst
  account_payment_order_return/static/description/icon.png
  account_payment_order_return/static/description/index.html
  account_payment_order_return/tests/__init__.py
  account_payment_order_return/tests/test_account_payment_order_return.py
  account_payment_order_return/wizards/__init__.py
  account_payment_order_return/wizards/account_payment_line_create.py
  account_payment_order_return/wizards/account_payment_line_create_view.xml
  oca_dependencies.txt
Labels: approved

#561 [FIX] 11.0 Account Payment Order: domain bug on create line wizard
  account_payment_order/__manifest__.py
  account_payment_order/models/account_invoice.py
  account_payment_order/models/account_move.py
  account_payment_order/models/account_move_line.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/models/account_payment_mode.py
  account_payment_order/models/account_payment_order.py
  account_payment_order/models/bank_payment_line.py
  account_payment_order/models/res_bank.py
  account_payment_order/wizard/account_invoice_payment_line_multi.py
  account_payment_order/wizard/account_payment_line_create.py
Labels: approved, ready to merge

#560 [12.0] [REF] Account Payment Order: split generate_move method
  account_payment_order/models/account_payment_order.py
Labels: approved, needs review, ready to merge

#581 [12.0][FIX] account_payment_order report
  account_payment_order/report/account_payment_order.xml
Labels: approved, ready to merge

#583 [11.0] account_banking_pain_base: Allow override of address block
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/models/account_payment_order.py
Labels: approved, ready to merge

#546 [11.0]Update invoice_supplier_form view
  account_payment_partner/views/account_invoice_view.xml
Labels: approved, ready to merge
