Repository OCA/bank-payment, pull requests merged in 2021-07, with the labels that each got.

#780 [12.0][IMP] account_banking_mandate: Improve code to unify search of valid mandate
  account_banking_mandate/models/account_move_line.py
  account_banking_mandate/models/res_partner.py
  account_banking_mandate/tests/test_invoice_mandate.py
Labels: approved, bot is merging ⏳, ready to merge

#827 [FIX] Add partner_bank_id validation in AccountMoveLine
  account_payment_order/models/account_move_line.py
Labels: approved, bot is merging ⏳

#573 [IMP] 10.0 bank_payment_order move invoice_ref calculation to python
  account_payment_order/report/account_payment_order.py
  account_payment_order/report/account_payment_order.xml
Labels: approved, bot is merging ⏳

#551 Add the button to mark as done a payment order.
  account_payment_order/views/account_payment_order.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#789 [12.0][NEW] Account Payment Repair
  account_payment_repair/README.rst
  account_payment_repair/__init__.py
  account_payment_repair/__manifest__.py
  account_payment_repair/models/__init__.py
  account_payment_repair/models/repair_order.py
  account_payment_repair/readme/CONFIGURE.rst
  account_payment_repair/readme/CONTRIBUTORS.rst
  account_payment_repair/readme/CREDITS.rst
  account_payment_repair/readme/DESCRIPTION.rst
  account_payment_repair/readme/USAGE.rst
  account_payment_repair/report/repair_report_templates.xml
  account_payment_repair/static/description/icon.png
  account_payment_repair/static/description/index.html
  account_payment_repair/tests/__init__.py
  account_payment_repair/tests/test_repair.py
  account_payment_repair/views/repair_order.xml
Labels: approved, bot is merging ⏳, ready to merge

#830 [14.0][IMP] account_payment_order: Add hook method for finding previous payment orders
  account_payment_order/README.rst
  account_payment_order/models/account_move.py
  account_payment_order/readme/CONTRIBUTORS.rst
  account_payment_order/static/description/index.html
Labels: approved, bot is merging ⏳

#832 [13.0][FIX] account_payment_partner: _compute_invoice_partner_bank isn't executed
  account_payment_partner/models/account_move.py
  account_payment_partner/tests/test_account_payment_partner.py
Labels: approved, bot is merging ⏳

#833 [13.0][FIX] account_payment_partner: _compute_invoice_partner_bank isn't executed
  account_payment_partner/models/account_move.py
Labels: approved, bot is merging ⏳

#835 [13.0][FIX] account_payment_partner: Cache missed error when compute before than create
  account_payment_partner/models/account_move.py
Labels: approved, bot is merging ⏳

#834 [14.0][IMP] account_payment_order: Improved a create_account_payment_line method.
  account_payment_order/models/account_move.py
Labels: approved, bot is merging ⏳

#836 [14.0][FIX] - account_banking_mandate: Fix migration script
  account_banking_mandate/migrations/14.0.1.0.0/post-migrate.py
Labels: approved, bot is merging ⏳

#821 [14.0][IMP]account_payment_order: payment date when adding transaction line manually
  account_payment_order/models/account_move_line.py
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: bot is merging ⏳

#837 [13.0][FIX]bank_payment: fix warning of _company_default_get
  account_banking_mandate/models/res_partner.py
Labels: approved, bot is merging ⏳, ready to merge

#840 [13.0][FIX] account_payment_partner: pass invoice_partner_bank_id correctly on account move create
  account_payment_partner/models/account_move.py
Labels: bot is merging ⏳

#841 [14.0][FIX] account_payment_partner: pass invoice_partner_bank_id correctly on account move create
  account_payment_partner/models/account_move.py
Labels: bot is merging ⏳
