Repository OCA/bank-payment, pull requests merged in 2021-01, with the labels that each got.

#761 [14.0] [MIG] account_banking_pain_base: Migration to v14
  account_banking_pain_base/README.rst
  account_banking_pain_base/__init__.py
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/i18n/account_banking_pain_base.pot
  account_banking_pain_base/i18n/de.po
  account_banking_pain_base/i18n/es.po
  account_banking_pain_base/i18n/es_AR.po
  account_banking_pain_base/i18n/fr.po
  account_banking_pain_base/i18n/hr.po
  account_banking_pain_base/i18n/it.po
  account_banking_pain_base/i18n/nb_NO.po
  account_banking_pain_base/i18n/nl.po
  account_banking_pain_base/i18n/pt_BR.po
  account_banking_pain_base/i18n/sl.po
  account_banking_pain_base/models/__init__.py
  account_banking_pain_base/models/account_payment_line.py
  account_banking_pain_base/models/account_payment_method.py
  account_banking_pain_base/models/account_payment_mode.py
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/models/bank_payment_line.py
  account_banking_pain_base/models/res_bank.py
  account_banking_pain_base/models/res_company.py
  account_banking_pain_base/models/res_config_settings.py
  account_banking_pain_base/post_install.py
  account_banking_pain_base/readme/CONFIGURE.rst
  account_banking_pain_base/readme/CONTRIBUTORS.rst
  account_banking_pain_base/readme/DESCRIPTION.rst
  account_banking_pain_base/readme/INSTALL.rst
  account_banking_pain_base/readme/USAGE.rst
  account_banking_pain_base/security/security.xml
  account_banking_pain_base/static/description/icon.png
  account_banking_pain_base/static/description/index.html
  account_banking_pain_base/views/account_payment_line.xml
  account_banking_pain_base/views/account_payment_method.xml
  account_banking_pain_base/views/account_payment_mode.xml
  account_banking_pain_base/views/account_payment_order.xml
  account_banking_pain_base/views/bank_payment_line_view.xml
  account_banking_pain_base/views/res_config_settings.xml
  requirements.txt
  setup/account_banking_pain_base/odoo/addons/account_banking_pain_base
  setup/account_banking_pain_base/setup.py
Labels: approved, bot is merging ⏳

#750 [13.0] [FIX] acount_payment_sale: set bank account only on out invoices
  account_payment_sale/models/account_move.py
Labels: approved, bot is merging ⏳, ready to merge

#772 [14.0] [MIG] account_banking_sepa_credit_transfer: Migration to v14
  account_banking_sepa_credit_transfer/README.rst
  account_banking_sepa_credit_transfer/__init__.py
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/data/account_payment_method.xml
  account_banking_sepa_credit_transfer/data/pain.001.001.02.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.03.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.04.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.05.xsd
  account_banking_sepa_credit_transfer/data/pain.001.003.03.xsd
  account_banking_sepa_credit_transfer/demo/sepa_credit_transfer_demo.xml
  account_banking_sepa_credit_transfer/i18n/account_banking_sepa_credit_transfer.pot
  account_banking_sepa_credit_transfer/i18n/de.po
  account_banking_sepa_credit_transfer/i18n/es.po
  account_banking_sepa_credit_transfer/i18n/es_AR.po
  account_banking_sepa_credit_transfer/i18n/fr.po
  account_banking_sepa_credit_transfer/i18n/hr.po
  account_banking_sepa_credit_transfer/i18n/nb_NO.po
  account_banking_sepa_credit_transfer/i18n/nl.po
  account_banking_sepa_credit_transfer/i18n/pt_BR.po
  account_banking_sepa_credit_transfer/i18n/sl.po
  account_banking_sepa_credit_transfer/models/__init__.py
  account_banking_sepa_credit_transfer/models/account_payment_line.py
  account_banking_sepa_credit_transfer/models/account_payment_method.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/post_install.py
  account_banking_sepa_credit_transfer/readme/CONFIGURE.rst
  account_banking_sepa_credit_transfer/readme/CONTRIBUTORS.rst
  account_banking_sepa_credit_transfer/readme/DESCRIPTION.rst
  account_banking_sepa_credit_transfer/readme/INSTALL.rst
  account_banking_sepa_credit_transfer/readme/USAGE.rst
  account_banking_sepa_credit_transfer/static/description/icon.png
  account_banking_sepa_credit_transfer/static/description/icon.svg
  account_banking_sepa_credit_transfer/static/description/index.html
  account_banking_sepa_credit_transfer/tests/__init__.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  setup/account_banking_sepa_credit_transfer/odoo/addons/account_banking_sepa_credit_transfer
  setup/account_banking_sepa_credit_transfer/setup.py
Labels: approved, bot is merging ⏳

#775 [14.0] [MIG] account_payment_purchase_stock: Migration to v14
  account_payment_purchase_stock/README.rst
  account_payment_purchase_stock/__init__.py
  account_payment_purchase_stock/__manifest__.py
  account_payment_purchase_stock/i18n/account_payment_purchase_stock.pot
  account_payment_purchase_stock/models/__init__.py
  account_payment_purchase_stock/models/stock_rule.py
  account_payment_purchase_stock/readme/CONTRIBUTORS.rst
  account_payment_purchase_stock/readme/DESCRIPTION.rst
  account_payment_purchase_stock/readme/INSTALL.rst
  account_payment_purchase_stock/readme/USAGE.rst
  account_payment_purchase_stock/static/description/icon.png
  account_payment_purchase_stock/static/description/index.html
  account_payment_purchase_stock/tests/__init__.py
  account_payment_purchase_stock/tests/test_account_payment_purchase_stock.py
  setup/account_payment_purchase_stock/odoo/addons/account_payment_purchase_stock
  setup/account_payment_purchase_stock/setup.py
Labels: bot is merging ⏳
