Repository OCA/bank-payment, pull requests merged in 2021-03, with the labels that each got.

#786 [14.0][FIX] account_payment_order + account_banking_mandate: Fix tests
  account_banking_mandate/tests/test_invoice_mandate.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳, ready to merge

#788 [14.0] account_banking_mandate: fix inherit of partner view
  account_banking_mandate/views/res_partner.xml
Labels: bot is merging ⏳

#791 [14.0][FIX] account_payment_partner: Set correct journal in tests to prevent error
  account_payment_partner/tests/test_account_payment_partner.py
Labels: approved, bot is merging ⏳

#790 [13.0][FIX] account_payment_partner: Set correct journal in tests to prevent error
  account_payment_order_return/tests/test_account_payment_order_return.py
  account_payment_partner/tests/test_account_payment_partner.py
Labels: approved, bot is merging ⏳

#793 [13.0][FIX] account_payment_order_return: Fix tests
  account_payment_order_return/tests/test_account_payment_order_return.py
Labels: approved, bot is merging ⏳

#796 [13.0][FIX] account_payment_partner + account_payment_sale: Fix multi-company issues
  account_payment_partner/models/res_partner.py
  account_payment_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#795 [14.0][MIG] account_payment_order_return: Migration to 14.0
  account_payment_order_return/README.rst
  account_payment_order_return/__init__.py
  account_payment_order_return/__manifest__.py
  account_payment_order_return/i18n/account_payment_order_return.pot
  account_payment_order_return/i18n/ca.po
  account_payment_order_return/i18n/ca_ES.po
  account_payment_order_return/i18n/de.po
  account_payment_order_return/i18n/es.po
  account_payment_order_return/i18n/fr.po
  account_payment_order_return/readme/CONTRIBUTORS.rst
  account_payment_order_return/readme/DESCRIPTION.rst
  account_payment_order_return/readme/INSTALL.rst
  account_payment_order_return/readme/USAGE.rst
  account_payment_order_return/static/description/icon.png
  account_payment_order_return/static/description/index.html
  account_payment_order_return/tests/__init__.py
  account_payment_order_return/tests/test_account_payment_order_return.py
  account_payment_order_return/wizards/__init__.py
  account_payment_order_return/wizards/account_payment_line_create.py
  account_payment_order_return/wizards/account_payment_line_create_view.xml
  setup/account_payment_order_return/odoo/addons/account_payment_order_return
  setup/account_payment_order_return/setup.py
Labels: approved, bot is merging ⏳

#797 [13.0][FIX] account_payment_order: Fix tests
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: bot is merging ⏳

#798 [13.0][FIX] account_payment_order: Fix tests
  account_payment_order/tests/test_payment_order_inbound.py
Labels: approved, bot is merging ⏳

#799 [14.0][FIX] account_payment_order: Fix tests
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳
