Repository OCA/bank-payment, pull requests merged in 2021-05, with the labels that each got.

#815 [14.0][IMP] account_payment_order - move date should be bank line date when offsetting_account is bank_account
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#522 [11.0] only generate FinInstId PstlAdr for some pain flavors
  account_banking_pain_base/models/account_payment_order.py
Labels: approved, bot is merging ⏳, needs review

#816 [14.0][FIX] account_payment_order: several minor fixes
  account_payment_order/security/payment_security.xml
  account_payment_order/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳

#716 ADD 13.0 account_invoice_select_for_payment
  account_invoice_select_for_payment/README.rst
  account_invoice_select_for_payment/__init__.py
  account_invoice_select_for_payment/__manifest__.py
  account_invoice_select_for_payment/models/__init__.py
  account_invoice_select_for_payment/models/account_move.py
  account_invoice_select_for_payment/models/account_payment.py
  account_invoice_select_for_payment/readme/CONTRIBUTORS.rst
  account_invoice_select_for_payment/readme/DESCRIPTION.rst
  account_invoice_select_for_payment/readme/USAGE.rst
  account_invoice_select_for_payment/static/description/index.html
  account_invoice_select_for_payment/views/account_move.xml
Labels: approved, bot is merging ⏳

#817 [14.0][FIX] account_payment_order: fix account move views
  account_payment_order/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#810 [13.0][IMP] account_payment_partner: Add refund_payment_mode_id to set in reverse moves.
  account_payment_partner/__manifest__.py
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_payment_mode.py
  account_payment_partner/models/res_partner.py
  account_payment_partner/readme/CONTRIBUTORS.rst
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳

#801 [13.0][IMP] account_payment_order: add the posibility to choose the payment…
  account_payment_order/models/account_move_line.py
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳, ready to merge

#819 [14.0][IMP] account_payment_partner: Add refund_payment_mode_id to set in reverse moves
  account_payment_partner/__manifest__.py
  account_payment_partner/i18n/account_payment_partner.pot
  account_payment_partner/i18n/es.po
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_payment_mode.py
  account_payment_partner/models/res_partner.py
  account_payment_partner/readme/CONTRIBUTORS.rst
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳, ready to merge
