Repository OCA/bank-payment, pull requests merged in 2022-09, with the labels that each got.

#955 [14.0][FIX] account_payment_purchase: Don't propagate empty payment mode
  account_payment_purchase/models/__init__.py
  account_payment_purchase/models/account_move.py
  account_payment_purchase/tests/test_account_payment_purchase.py
Labels: approved, bot is merging ⏳

#936 [FIX]account_payment_order
  account_payment_order/models/account_move_line.py
Labels: approved, ready to merge, bot is merging ⏳

#946 [13.0][MIG] account_payment_order_tier_validation: Migration to 13.0 from 14.0
  account_payment_order_tier_validation/README.rst
  account_payment_order_tier_validation/__init__.py
  account_payment_order_tier_validation/__manifest__.py
  account_payment_order_tier_validation/models/__init__.py
  account_payment_order_tier_validation/models/account_payment_order.py
  account_payment_order_tier_validation/models/tier_definition.py
  account_payment_order_tier_validation/readme/CONFIGURE.rst
  account_payment_order_tier_validation/readme/CONTRIBUTORS.rst
  account_payment_order_tier_validation/readme/DESCRIPTION.rst
  account_payment_order_tier_validation/readme/INSTALL.rst
  account_payment_order_tier_validation/readme/USAGE.rst
  account_payment_order_tier_validation/static/description/icon.png
  account_payment_order_tier_validation/static/description/index.html
  account_payment_order_tier_validation/tests/__init__.py
  account_payment_order_tier_validation/tests/test_payment_order_tier_validation.py
  account_payment_order_tier_validation/views/account_payment_order.xml
  setup/account_payment_order_tier_validation/odoo/addons/account_payment_order_tier_validation
  setup/account_payment_order_tier_validation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#945 [12.0][MIG] account_payment_order_tier_validation: Migration to 12.0 from 14.0
  account_payment_order_tier_validation/README.rst
  account_payment_order_tier_validation/__init__.py
  account_payment_order_tier_validation/__manifest__.py
  account_payment_order_tier_validation/models/__init__.py
  account_payment_order_tier_validation/models/account_payment_order.py
  account_payment_order_tier_validation/models/tier_definition.py
  account_payment_order_tier_validation/readme/CONFIGURE.rst
  account_payment_order_tier_validation/readme/CONTRIBUTORS.rst
  account_payment_order_tier_validation/readme/DESCRIPTION.rst
  account_payment_order_tier_validation/readme/INSTALL.rst
  account_payment_order_tier_validation/readme/USAGE.rst
  account_payment_order_tier_validation/static/description/icon.png
  account_payment_order_tier_validation/static/description/index.html
  account_payment_order_tier_validation/tests/__init__.py
  account_payment_order_tier_validation/tests/test_payment_order_tier_validation.py
  account_payment_order_tier_validation/views/account_payment_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#954 [WIP][ADD] account_payment_order_sequence_payment_mode
  account_payment_order_sequence_payment_mode/README.rst
  account_payment_order_sequence_payment_mode/__init__.py
  account_payment_order_sequence_payment_mode/__manifest__.py
  account_payment_order_sequence_payment_mode/models/__init__.py
  account_payment_order_sequence_payment_mode/models/account_payment_mode.py
  account_payment_order_sequence_payment_mode/models/account_payment_order.py
  account_payment_order_sequence_payment_mode/readme/CONTRIBUTORS.rst
  account_payment_order_sequence_payment_mode/readme/DESCRIPTION.rst
  account_payment_order_sequence_payment_mode/readme/USAGE.rst
  account_payment_order_sequence_payment_mode/static/description/index.html
  account_payment_order_sequence_payment_mode/views/account_payment_mode.xml
  setup/account_payment_order_sequence_payment_mode/odoo/addons/account_payment_order_sequence_payment_mode
  setup/account_payment_order_sequence_payment_mode/setup.py
Labels: approved, bot is merging ⏳

#911 [ENH][14.0] bank-payment Fallback to payment_ref if ref is undefined
  account_payment_order/report/account_payment_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#958 [13.0][FIX] account_payment_order: Open the payment order created from the selected invoices.
  account_payment_order/models/account_move.py
Labels: bot is merging ⏳

#959 [15.0][FIX] account_payment_order: small usability fix
  account_payment_order/models/account_move.py
Labels: bot is merging ⏳

#961 [14.0][FIX] account_payment_order: Restore payment order number in account move line label
  account_payment_order/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#962 [15.0][FIX] account_payment_order: Restore payment order number in account move line label.
  account_payment_order/models/account_payment_order.py
Labels: bot is merging ⏳
