Repository OCA/bank-payment, pull requests merged in 2022-04, with the labels that each got.

#913 [15.0][MIG]account_payment_sale
  account_payment_sale/README.rst
  account_payment_sale/__init__.py
  account_payment_sale/__manifest__.py
  account_payment_sale/i18n/account_payment_sale.pot
  account_payment_sale/i18n/ca.po
  account_payment_sale/i18n/da_DK.po
  account_payment_sale/i18n/de.po
  account_payment_sale/i18n/es.po
  account_payment_sale/i18n/es_AR.po
  account_payment_sale/i18n/fr.po
  account_payment_sale/i18n/fr_FR.po
  account_payment_sale/i18n/it.po
  account_payment_sale/i18n/nl.po
  account_payment_sale/i18n/nl_NL.po
  account_payment_sale/i18n/pt_BR.po
  account_payment_sale/i18n/sl.po
  account_payment_sale/i18n/sv.po
  account_payment_sale/i18n/zh_CN.po
  account_payment_sale/models/__init__.py
  account_payment_sale/models/sale_order.py
  account_payment_sale/readme/CONTRIBUTORS.rst
  account_payment_sale/readme/DESCRIPTION.rst
  account_payment_sale/readme/USAGE.rst
  account_payment_sale/static/description/icon.png
  account_payment_sale/static/description/index.html
  account_payment_sale/tests/__init__.py
  account_payment_sale/tests/common.py
  account_payment_sale/tests/test_sale_order.py
  account_payment_sale/views/sale_order_view.xml
  account_payment_sale/views/sale_report_templates.xml
  account_payment_sale/wizard/__init__.py
  account_payment_sale/wizard/sale_make_invoice_advance.py
  setup/account_payment_sale/odoo/addons/account_payment_sale
  setup/account_payment_sale/setup.py
Labels: approved, bot is merging ⏳

#912 [15.0][MIG]account_banking_pain_base
  account_banking_pain_base/README.rst
  account_banking_pain_base/__init__.py
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/i18n/account_banking_pain_base.pot
  account_banking_pain_base/i18n/de.po
  account_banking_pain_base/i18n/es.po
  account_banking_pain_base/i18n/es_AR.po
  account_banking_pain_base/i18n/fr.po
  account_banking_pain_base/i18n/hr.po
  account_banking_pain_base/i18n/it.po
  account_banking_pain_base/i18n/nb_NO.po
  account_banking_pain_base/i18n/nl.po
  account_banking_pain_base/i18n/pt_BR.po
  account_banking_pain_base/i18n/sl.po
  account_banking_pain_base/i18n/sv.po
  account_banking_pain_base/models/__init__.py
  account_banking_pain_base/models/account_payment_line.py
  account_banking_pain_base/models/account_payment_method.py
  account_banking_pain_base/models/account_payment_mode.py
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/models/bank_payment_line.py
  account_banking_pain_base/models/res_bank.py
  account_banking_pain_base/models/res_company.py
  account_banking_pain_base/models/res_config_settings.py
  account_banking_pain_base/post_install.py
  account_banking_pain_base/readme/CONFIGURE.rst
  account_banking_pain_base/readme/CONTRIBUTORS.rst
  account_banking_pain_base/readme/DESCRIPTION.rst
  account_banking_pain_base/readme/INSTALL.rst
  account_banking_pain_base/readme/USAGE.rst
  account_banking_pain_base/security/security.xml
  account_banking_pain_base/static/description/icon.png
  account_banking_pain_base/static/description/index.html
  account_banking_pain_base/views/account_payment_line.xml
  account_banking_pain_base/views/account_payment_method.xml
  account_banking_pain_base/views/account_payment_mode.xml
  account_banking_pain_base/views/account_payment_order.xml
  account_banking_pain_base/views/bank_payment_line_view.xml
  account_banking_pain_base/views/res_config_settings.xml
  requirements.txt
  setup/account_banking_pain_base/odoo/addons/account_banking_pain_base
  setup/account_banking_pain_base/setup.py
Labels: approved, bot is merging ⏳

#915 [15.0][MIG]account_banking_sepa_direct_debit
  account_banking_sepa_direct_debit/README.rst
  account_banking_sepa_direct_debit/__init__.py
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/data/account_payment_method.xml
  account_banking_sepa_direct_debit/data/mandate_expire_cron.xml
  account_banking_sepa_direct_debit/data/pain.008.001.02.xsd
  account_banking_sepa_direct_debit/data/pain.008.001.03.xsd
  account_banking_sepa_direct_debit/data/pain.008.001.04.xsd
  account_banking_sepa_direct_debit/data/pain.008.003.02.xsd
  account_banking_sepa_direct_debit/data/report_paperformat.xml
  account_banking_sepa_direct_debit/demo/sepa_direct_debit_demo.xml
  account_banking_sepa_direct_debit/i18n/account_banking_sepa_direct_debit.pot
  account_banking_sepa_direct_debit/i18n/de.po
  account_banking_sepa_direct_debit/i18n/es.po
  account_banking_sepa_direct_debit/i18n/es_AR.po
  account_banking_sepa_direct_debit/i18n/fr.po
  account_banking_sepa_direct_debit/i18n/hr.po
  account_banking_sepa_direct_debit/i18n/it.po
  account_banking_sepa_direct_debit/i18n/nb_NO.po
  account_banking_sepa_direct_debit/i18n/nl.po
  account_banking_sepa_direct_debit/i18n/pt_BR.po
  account_banking_sepa_direct_debit/i18n/sl.po
  account_banking_sepa_direct_debit/models/__init__.py
  account_banking_sepa_direct_debit/models/account_banking_mandate.py
  account_banking_sepa_direct_debit/models/account_payment_line.py
  account_banking_sepa_direct_debit/models/account_payment_method.py
  account_banking_sepa_direct_debit/models/account_payment_mode.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_banking_sepa_direct_debit/models/bank_payment_line.py
  account_banking_sepa_direct_debit/models/res_company.py
  account_banking_sepa_direct_debit/post_install.py
  account_banking_sepa_direct_debit/readme/CONFIGURE.rst
  account_banking_sepa_direct_debit/readme/CONTRIBUTORS.rst
  account_banking_sepa_direct_debit/readme/DESCRIPTION.rst
  account_banking_sepa_direct_debit/readme/INSTALL.rst
  account_banking_sepa_direct_debit/readme/USAGE.rst
  account_banking_sepa_direct_debit/reports/sepa_direct_debit_mandate.xml
  account_banking_sepa_direct_debit/static/description/icon.png
  account_banking_sepa_direct_debit/static/description/icon.svg
  account_banking_sepa_direct_debit/static/description/index.html
  account_banking_sepa_direct_debit/static/src/css/report.css
  account_banking_sepa_direct_debit/tests/__init__.py
  account_banking_sepa_direct_debit/tests/test_mandate.py
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_banking_sepa_direct_debit/views/account_banking_mandate_view.xml
  account_banking_sepa_direct_debit/views/account_payment_mode.xml
  account_banking_sepa_direct_debit/views/report_sepa_direct_debit_mandate.xml
  account_banking_sepa_direct_debit/views/res_config_settings.xml
  account_banking_sepa_direct_debit/wizards/__init__.py
  account_banking_sepa_direct_debit/wizards/res_config_settings.py
  requirements.txt
  setup/account_banking_sepa_direct_debit/odoo/addons/account_banking_sepa_direct_debit
  setup/account_banking_sepa_direct_debit/setup.py
Labels: approved, bot is merging ⏳

#918 [14.0] account_payment_order: Better communication field management
  account_payment_order/models/account_move_line.py
  account_payment_order/readme/CONTRIBUTORS.rst
  account_payment_order/tests/test_account_payment.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: bot is merging ⏳

#922 Promote Banking modules to Mature
  account_payment_mode/__manifest__.py
  account_payment_order/__manifest__.py
  account_payment_partner/__manifest__.py
Labels: bot is merging ⏳

#923 Promote some modules
  account_payment_mode/__manifest__.py
  account_payment_order/__manifest__.py
  account_payment_partner/__manifest__.py
Labels: bot is merging ⏳

#924 Promote some modules
  account_payment_mode/__manifest__.py
  account_payment_order/__manifest__.py
  account_payment_partner/__manifest__.py
Labels: bot is merging ⏳

#925 [13.0][FIX] account_payment_order: Don't fail due to tz
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order_return/tests/test_account_payment_order_return.py
Labels: bot is merging ⏳

#919 [14.0][IMP] account_payment_order: Add existing payment references to communication
  account_payment_order/models/account_move_line.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, ready to merge, bot is merging ⏳

#900 [14.0][FIX] account_payment_purchase: solved error get payment mode and ban…
  account_payment_purchase/models/account_invoice.py
Labels: approved, ready to merge, bot is merging ⏳
