Repository OCA/bank-payment, pull requests merged in 2022-02, with the labels that each got.

#873 [15.0] [MIG] account_payment_partner
  account_payment_partner/README.rst
  account_payment_partner/__init__.py
  account_payment_partner/__manifest__.py
  account_payment_partner/demo/partner_demo.xml
  account_payment_partner/i18n/account_payment_partner.pot
  account_payment_partner/i18n/ca.po
  account_payment_partner/i18n/da_DK.po
  account_payment_partner/i18n/de.po
  account_payment_partner/i18n/es.po
  account_payment_partner/i18n/es_AR.po
  account_payment_partner/i18n/es_CL.po
  account_payment_partner/i18n/fr.po
  account_payment_partner/i18n/fr_FR.po
  account_payment_partner/i18n/hr.po
  account_payment_partner/i18n/it.po
  account_payment_partner/i18n/nb_NO.po
  account_payment_partner/i18n/nl.po
  account_payment_partner/i18n/pt.po
  account_payment_partner/i18n/pt_BR.po
  account_payment_partner/i18n/sl.po
  account_payment_partner/i18n/sv.po
  account_payment_partner/models/__init__.py
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_move_line.py
  account_payment_partner/models/account_payment_mode.py
  account_payment_partner/models/res_partner.py
  account_payment_partner/readme/CONTRIBUTORS.rst
  account_payment_partner/readme/DESCRIPTION.rst
  account_payment_partner/readme/HISTORY.rst
  account_payment_partner/readme/USAGE.rst
  account_payment_partner/reports/__init__.py
  account_payment_partner/reports/account_invoice_report.py
  account_payment_partner/reports/account_invoice_report_view.xml
  account_payment_partner/static/description/icon.png
  account_payment_partner/static/description/index.html
  account_payment_partner/tests/__init__.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_move_line.xml
  account_payment_partner/views/account_move_view.xml
  account_payment_partner/views/account_payment_mode.xml
  account_payment_partner/views/report_invoice.xml
  account_payment_partner/views/res_partner_view.xml
  setup/account_payment_partner/odoo/addons/account_payment_partner
  setup/account_payment_partner/setup.py
Labels: bot is merging ⏳

#897 [14.0] account_payment_order: communication required in form view
  account_payment_order/models/account_payment_line.py
  account_payment_order/views/account_payment_line.xml
Labels: bot is merging ⏳

#776 [ADD][14.0] account_payment_order_vendor_email
  account_payment_order_vendor_email/README.rst
  account_payment_order_vendor_email/__init__.py
  account_payment_order_vendor_email/__manifest__.py
  account_payment_order_vendor_email/data/mail_template.xml
  account_payment_order_vendor_email/models/__init__.py
  account_payment_order_vendor_email/models/account_payment_mode.py
  account_payment_order_vendor_email/readme/CONTRIBUTORS.rst
  account_payment_order_vendor_email/readme/DESCRIPTION.rst
  account_payment_order_vendor_email/readme/USAGE.rst
  account_payment_order_vendor_email/static/description/icon.png
  account_payment_order_vendor_email/tests/__init__.py
  account_payment_order_vendor_email/tests/test_account_payment_order_vendor_mail.py
  account_payment_order_vendor_email/views/account_payment_mode_view.xml
  account_payment_order_vendor_email/views/account_payment_order_view.xml
  setup/account_payment_order_vendor_email/odoo/addons/account_payment_order_vendor_email
  setup/account_payment_order_vendor_email/setup.py
Labels: enhancement, bot is merging ⏳

#901 [FIX] [14.0] Removed external dependencies already defined in Odoo base
  account_banking_sepa_direct_debit/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳
