Repository OCA/bank-payment, pull requests merged in 2022-11, with the labels that each got.

#981 [14.0][IMP] account_payment_order: add link to payment order in chatter
  account_payment_order/models/account_move.py
Labels: approved, bot is merging ⏳

#983 [14.0][MIG] account_payment_order_notification: Migration to 14.0
  account_payment_order_notification/README.rst
  account_payment_order_notification/__init__.py
  account_payment_order_notification/__manifest__.py
  account_payment_order_notification/data/mail_template_data.xml
  account_payment_order_notification/i18n/account_payment_order_notification.pot
  account_payment_order_notification/i18n/es.po
  account_payment_order_notification/models/__init__.py
  account_payment_order_notification/models/account_payment_order.py
  account_payment_order_notification/models/account_payment_order_notification.py
  account_payment_order_notification/readme/CONFIGURE.rst
  account_payment_order_notification/readme/CONTRIBUTORS.rst
  account_payment_order_notification/readme/DESCRIPTION.rst
  account_payment_order_notification/readme/USAGE.rst
  account_payment_order_notification/security/ir.model.access.csv
  account_payment_order_notification/static/description/icon.png
  account_payment_order_notification/static/description/index.html
  account_payment_order_notification/tests/__init__.py
  account_payment_order_notification/tests/test_account_payment_order_notification.py
  account_payment_order_notification/views/account_payment_order_notification_view.xml
  account_payment_order_notification/views/account_payment_order_view.xml
  account_payment_order_notification/wizard/__init__.py
  account_payment_order_notification/wizard/wizard_account_payment_order_notification.py
  account_payment_order_notification/wizard/wizard_account_payment_order_notification_views.xml
  setup/account_payment_order_notification/odoo/addons/account_payment_order_notification
  setup/account_payment_order_notification/setup.py
Labels: approved, bot is merging ⏳

#976 [15.0][IMP]account_payment_order: Add activities to account.payment.order model
  account_payment_order/models/account_payment_order.py
  account_payment_order/views/account_payment_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#984 [13.0][FIX] account_payment_order_notification: Create notification with the correct partner (invoice partner).
  account_payment_order_notification/tests/test_account_payment_order_notification.py
  account_payment_order_notification/wizard/wizard_account_payment_order_notification.py
Labels: bot is merging ⏳

#988 [14.0][FIX] account_payment_order_notification: Create notification with the correct partner (invoice partner).
  account_payment_order_notification/tests/test_account_payment_order_notification.py
  account_payment_order_notification/wizard/wizard_account_payment_order_notification.py
Labels: approved, bot is merging ⏳
