Repository OCA/bank-payment, pull requests merged in 2022-12, with the labels that each got.

#884 [15.0][MIG] account_banking_mandate_sale
  account_banking_mandate_sale/README.rst
  account_banking_mandate_sale/__init__.py
  account_banking_mandate_sale/__manifest__.py
  account_banking_mandate_sale/i18n/account_banking_mandate_sale.pot
  account_banking_mandate_sale/i18n/ca.po
  account_banking_mandate_sale/i18n/ca_ES.po
  account_banking_mandate_sale/i18n/de.po
  account_banking_mandate_sale/i18n/es.po
  account_banking_mandate_sale/i18n/hr.po
  account_banking_mandate_sale/i18n/nl.po
  account_banking_mandate_sale/i18n/nl_NL.po
  account_banking_mandate_sale/i18n/pt_BR.po
  account_banking_mandate_sale/i18n/sl.po
  account_banking_mandate_sale/models/__init__.py
  account_banking_mandate_sale/models/sale_order.py
  account_banking_mandate_sale/oca_dependencies.txt
  account_banking_mandate_sale/readme/CONFIGURATION.rst
  account_banking_mandate_sale/readme/CONTRIBUTORS.rst
  account_banking_mandate_sale/readme/DESCRIPTION.rst
  account_banking_mandate_sale/readme/USAGE.rst
  account_banking_mandate_sale/static/description/icon.png
  account_banking_mandate_sale/static/description/index.html
  account_banking_mandate_sale/views/sale_order.xml
  account_banking_mandate_sale/wizard/__init__.py
  account_banking_mandate_sale/wizard/sale_make_invoice_advance.py
  setup/account_banking_mandate_sale/odoo/addons/account_banking_mandate_sale
  setup/account_banking_mandate_sale/setup.py
Labels: bot is merging ⏳

#995 [IMP] account_banking_mandate: change development_status to Production
  account_banking_mandate/__manifest__.py
Labels: approved, bot is merging ⏳

#994 [15.0][ADD] account_banking_mandate_contact: new module
  account_banking_mandate_contact/README.rst
  account_banking_mandate_contact/__init__.py
  account_banking_mandate_contact/__manifest__.py
  account_banking_mandate_contact/i18n/account_banking_mandate_contact.pot
  account_banking_mandate_contact/i18n/es.po
  account_banking_mandate_contact/models/__init__.py
  account_banking_mandate_contact/models/account_move_line.py
  account_banking_mandate_contact/models/res_partner.py
  account_banking_mandate_contact/readme/CONTRIBUTORS.rst
  account_banking_mandate_contact/readme/DESCRIPTION.rst
  account_banking_mandate_contact/readme/USAGE.rst
  account_banking_mandate_contact/static/description/icon.png
  account_banking_mandate_contact/static/description/index.html
  account_banking_mandate_contact/tests/__init__.py
  account_banking_mandate_contact/tests/test_account_payment_order.py
  account_banking_mandate_contact/views/res_partner.xml
  setup/account_banking_mandate_contact/odoo/addons/account_banking_mandate_contact
  setup/account_banking_mandate_contact/setup.py
Labels: approved, bot is merging ⏳

#997 [14.0][MIG] account_banking_mandate_contact: Migration to version 14.0
  account_banking_mandate_contact/README.rst
  account_banking_mandate_contact/__init__.py
  account_banking_mandate_contact/__manifest__.py
  account_banking_mandate_contact/i18n/account_banking_mandate_contact.pot
  account_banking_mandate_contact/i18n/es.po
  account_banking_mandate_contact/models/__init__.py
  account_banking_mandate_contact/models/account_move_line.py
  account_banking_mandate_contact/models/res_partner.py
  account_banking_mandate_contact/readme/CONTRIBUTORS.rst
  account_banking_mandate_contact/readme/DESCRIPTION.rst
  account_banking_mandate_contact/readme/USAGE.rst
  account_banking_mandate_contact/static/description/icon.png
  account_banking_mandate_contact/static/description/index.html
  account_banking_mandate_contact/tests/__init__.py
  account_banking_mandate_contact/tests/test_account_payment_order.py
  account_banking_mandate_contact/views/res_partner.xml
  setup/account_banking_mandate_contact/odoo/addons/account_banking_mandate_contact
  setup/account_banking_mandate_contact/setup.py
Labels: approved, bot is merging ⏳

#1000 [FIX] account_payment_order: Error in Batch Payments when deleting a Batch Content line
  account_payment_order/models/account_payment.py
Labels: bot is merging ⏳

#998 [14.0][FIX] [URGENT] generate pain address block that is supported by german banks
  account_banking_pain_base/models/account_payment_order.py
  account_banking_sepa_credit_transfer/models/account_payment_method.py
Labels: approved, bot is merging ⏳

#1003 [15.0][FIX] [URGENT] generate pain address block that is supported by german banks
  account_banking_pain_base/models/account_payment_order.py
  account_banking_sepa_credit_transfer/models/account_payment_method.py
Labels: bot is merging ⏳

#991 [15.0][MIG] account_payment_purchase_stock
  account_payment_purchase_stock/README.rst
  account_payment_purchase_stock/__init__.py
  account_payment_purchase_stock/__manifest__.py
  account_payment_purchase_stock/i18n/account_payment_purchase_stock.pot
  account_payment_purchase_stock/i18n/es_AR.po
  account_payment_purchase_stock/i18n/fr_FR.po
  account_payment_purchase_stock/i18n/it.po
  account_payment_purchase_stock/models/__init__.py
  account_payment_purchase_stock/models/stock_rule.py
  account_payment_purchase_stock/readme/CONTRIBUTORS.rst
  account_payment_purchase_stock/readme/DESCRIPTION.rst
  account_payment_purchase_stock/readme/INSTALL.rst
  account_payment_purchase_stock/readme/USAGE.rst
  account_payment_purchase_stock/static/description/icon.png
  account_payment_purchase_stock/static/description/index.html
  account_payment_purchase_stock/tests/__init__.py
  account_payment_purchase_stock/tests/test_account_payment_purchase_stock.py
  setup/account_payment_purchase_stock/odoo/addons/account_payment_purchase_stock
  setup/account_payment_purchase_stock/setup.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#1005 [13.0][FIX] account_banking_pain_base: Proper condition for AdrLine
  account_banking_pain_base/models/account_payment_order.py
Labels: bot is merging ⏳

#937 [14.0][Add] Create module account_payment_mode_default_account
  account_payment_mode_default_account/__init__.py
  account_payment_mode_default_account/__manifest__.py
  account_payment_mode_default_account/hooks.py
  account_payment_mode_default_account/models/__init__.py
  account_payment_mode_default_account/models/account_move.py
  account_payment_mode_default_account/models/account_payment_mode.py
  account_payment_mode_default_account/models/chart_template.py
  account_payment_mode_default_account/models/res_partner.py
  account_payment_mode_default_account/readme/CONTRIBUTORS.rst
  account_payment_mode_default_account/readme/DESCRIPTION.rst
  account_payment_mode_default_account/tests/__init__.py
  account_payment_mode_default_account/tests/test_account_payment_mode_default_account.py
  account_payment_mode_default_account/views/account_payment_mode.xml
  setup/account_payment_mode_default_account/odoo/addons/account_payment_mode_default_account
  setup/account_payment_mode_default_account/setup.py
Labels: approved, bot is merging ⏳
