Repository OCA/bank-payment, pull requests merged in 2023-01, with the labels that each got.

#979 [14.0][REF] account_payment_*: Use native payment object
  account_banking_mandate/__manifest__.py
  account_banking_mandate/models/__init__.py
  account_banking_mandate/models/bank_payment_line.py
  account_banking_mandate/tests/test_invoice_mandate.py
  account_banking_mandate/views/bank_payment_line_view.xml
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/models/__init__.py
  account_banking_pain_base/models/account_payment_line.py
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/models/bank_payment_line.py
  account_banking_pain_base/views/bank_payment_line_view.xml
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/models/__init__.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_banking_sepa_direct_debit/models/bank_payment_line.py
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_payment_order/__manifest__.py
  account_payment_order/data/payment_seq.xml
  account_payment_order/migrations/14.0.2.0.0/post-migration.py
  account_payment_order/models/__init__.py
  account_payment_order/models/account_move_line.py
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/models/account_payment_order.py
  account_payment_order/models/bank_payment_line.py
  account_payment_order/security/ir.model.access.csv
  account_payment_order/security/payment_security.xml
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_move_line.xml
  account_payment_order/views/account_payment_line.xml
  account_payment_order/views/account_payment_order.xml
  account_payment_order/views/bank_payment_line.xml
  account_payment_order_vendor_email/models/account_payment_mode.py
Labels: bot is merging ⏳

#1009 [16.0][FIX] account_payment_partner: fix error in _reverse_moves
  account_payment_partner/models/account_move.py
Labels: bot is merging ⏳

#967 [13.0][IMP] account_payment_partner: Make payment mode editable on journal item
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_move_line.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_move_line.xml
  account_payment_partner/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1020 [14.0][IMP] account_payment_partner: Make payment mode editable
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_move_line.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_move_line.xml
  account_payment_partner/views/account_move_view.xml
Labels: bot is merging ⏳

#1023 [15.0][IMP] account_payment_partner: Make payment mode editable
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_move_line.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_move_line.xml
  account_payment_partner/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1024 [16.0][IMP] account_payment_partner: Make payment mode editable
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_move_line.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_move_line.xml
  account_payment_partner/views/account_move_view.xml
Labels: approved, bot is merging ⏳
