Repository OCA/bank-payment, pull requests merged in 2023-05, with the labels that each got.

#1076 [16.0] [FIX] Payment Transaction view
  account_payment_order/views/account_payment_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#1068 [16.0][FIX] account_banking_mandate: move's create should be overrided properly to avoid flush_recordset
  account_banking_mandate/models/account_move.py
  account_banking_mandate/tests/test_invoice_mandate.py
Labels: approved, ready to merge, bot is merging ⏳

#1013 [FIX] account_payment_order: show tree view correctly when more than 1 Payment order are created
  account_payment_order/models/account_move.py
Labels: bot is merging ⏳, stale

#1081 [15.0][FIX] account_banking_pain_base: Proper condition for AdrLine
  account_banking_pain_base/models/account_payment_order.py
Labels: bot is merging ⏳

#1082 [15.0][FIX] account_payment_order: Set payment method line for account.payment
  account_payment_order/models/account_payment_line.py
Labels: approved, bot is merging ⏳

#1083 [16.0][FIX] account_payment_order: Set payment method line for account.payment
  account_payment_order/models/account_payment_line.py
Labels: bot is merging ⏳

#1084 [15.0][FIX] account_banking_sepa_credit_transfer: fix inactive currency error in the tests
  account_banking_sepa_credit_transfer/tests/test_sct.py
Labels: bot is merging ⏳

#1087 [16.0][MIG] account_banking_pain_base: Migration to 16.0
  account_banking_pain_base/README.rst
  account_banking_pain_base/__init__.py
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/i18n/account_banking_pain_base.pot
  account_banking_pain_base/i18n/ca.po
  account_banking_pain_base/i18n/de.po
  account_banking_pain_base/i18n/es.po
  account_banking_pain_base/i18n/es_AR.po
  account_banking_pain_base/i18n/fr.po
  account_banking_pain_base/i18n/hr.po
  account_banking_pain_base/i18n/it.po
  account_banking_pain_base/i18n/nb_NO.po
  account_banking_pain_base/i18n/nl.po
  account_banking_pain_base/i18n/pt_BR.po
  account_banking_pain_base/i18n/sl.po
  account_banking_pain_base/i18n/sv.po
  account_banking_pain_base/models/__init__.py
  account_banking_pain_base/models/account_payment_line.py
  account_banking_pain_base/models/account_payment_method.py
  account_banking_pain_base/models/account_payment_mode.py
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/models/res_bank.py
  account_banking_pain_base/models/res_company.py
  account_banking_pain_base/models/res_config_settings.py
  account_banking_pain_base/post_install.py
  account_banking_pain_base/readme/CONFIGURE.rst
  account_banking_pain_base/readme/CONTRIBUTORS.rst
  account_banking_pain_base/readme/DESCRIPTION.rst
  account_banking_pain_base/readme/INSTALL.rst
  account_banking_pain_base/readme/USAGE.rst
  account_banking_pain_base/security/security.xml
  account_banking_pain_base/static/description/icon.png
  account_banking_pain_base/static/description/index.html
  account_banking_pain_base/views/account_payment_line.xml
  account_banking_pain_base/views/account_payment_method.xml
  account_banking_pain_base/views/account_payment_mode.xml
  account_banking_pain_base/views/account_payment_order.xml
  account_banking_pain_base/views/res_config_settings.xml
  requirements.txt
  setup/account_banking_pain_base/odoo/addons/account_banking_pain_base
  setup/account_banking_pain_base/setup.py
Labels: bot is merging ⏳
