Repository OCA/bank-payment, pull requests merged in 2023-10, with the labels that each got.

#1153 [15.0][FIX+IMP] account_payment_order: Define the value of the communication field correctly
  account_payment_order/__manifest__.py
  account_payment_order/models/account_move.py
  account_payment_order/models/account_move_line.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_order.xml
  account_payment_order/views/account_payment_views.xml
Labels: approved, bot is merging ⏳

#1155 [16.0][FIX+IMP] account_payment_order: Define the value of the communication field correctly
  account_payment_order/__manifest__.py
  account_payment_order/models/account_move.py
  account_payment_order/models/account_move_line.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_order.xml
  account_payment_order/views/account_payment_views.xml
Labels: approved, bot is merging ⏳

#1151 [14.0][FIX] account_payment_order: Remove readonly=1 to move lines to allow to remove records
  account_payment_order/wizard/account_payment_line_create_view.xml
Labels: bot is merging ⏳

#1156 [15.0][FIX] account_payment_order: Remove readonly=1 to move lines to allow to remove records
  account_payment_order/wizard/account_payment_line_create_view.xml
Labels: bot is merging ⏳

#1157 [15.0][IMP] account_banking_mandate: Display mandate_id field in the form view of account.payment.line with the same condition as the tree view.
  account_banking_mandate/views/account_payment_line.xml
Labels: approved, bot is merging ⏳

#1158 [16.0][IMP] account_banking_mandate: Display mandate_id field in the form view of account.payment.line with the same condition as the tree view.
  account_banking_mandate/views/account_payment_line.xml
Labels: approved, bot is merging ⏳

#1159 [15.0][IMP] bank-payment : test performance improvement
  account_banking_mandate/tests/test_invoice_mandate.py
  account_banking_mandate/tests/test_mandate.py
  account_banking_mandate_contact/tests/test_account_payment_order.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_banking_sepa_direct_debit/tests/test_mandate.py
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_payment_mode/tests/test_account_payment_mode.py
  account_payment_order/tests/test_account_payment.py
  account_payment_order/tests/test_bank.py
  account_payment_order/tests/test_payment_mode.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order_return/tests/test_account_payment_order_return.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_sale/tests/common.py
  account_payment_sale/tests/test_sale_order.py
Labels: bot is merging ⏳

#1162 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_banking_mandate/i18n/account_banking_mandate.pot
  account_banking_mandate/views/account_banking_mandate_view.xml
  account_banking_pain_base/i18n/de.po
  account_banking_pain_base/i18n/es.po
  account_banking_pain_base/i18n/it.po
  account_banking_pain_base/i18n/nl.po
  account_banking_sepa_direct_debit/demo/sepa_direct_debit_demo.xml
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/views/account_payment_line.xml
  account_payment_order/views/account_payment_order.xml
  account_payment_order_notification/i18n/account_payment_order_notification.pot
  account_payment_order_tier_validation/i18n/account_payment_order_tier_validation.pot
Labels: needs review

#1038 [14.0][IMP] account_payment_order: Allow fixed date in the past
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_order.xml
Labels: approved, bot is merging ⏳
