Repository OCA/bank-payment, pull requests merged in 2023-06, with the labels that each got.

#1063 [16.0][MIG] account_payment_purchase_stock
  account_payment_purchase_stock/README.rst
  account_payment_purchase_stock/__init__.py
  account_payment_purchase_stock/__manifest__.py
  account_payment_purchase_stock/i18n/account_payment_purchase_stock.pot
  account_payment_purchase_stock/i18n/es_AR.po
  account_payment_purchase_stock/i18n/fr_FR.po
  account_payment_purchase_stock/i18n/it.po
  account_payment_purchase_stock/models/__init__.py
  account_payment_purchase_stock/models/stock_rule.py
  account_payment_purchase_stock/readme/CONTRIBUTORS.rst
  account_payment_purchase_stock/readme/DESCRIPTION.rst
  account_payment_purchase_stock/readme/INSTALL.rst
  account_payment_purchase_stock/readme/USAGE.rst
  account_payment_purchase_stock/static/description/icon.png
  account_payment_purchase_stock/static/description/index.html
  account_payment_purchase_stock/tests/__init__.py
  account_payment_purchase_stock/tests/test_account_payment_purchase_stock.py
  setup/account_payment_purchase_stock/odoo/addons/account_payment_purchase_stock
  setup/account_payment_purchase_stock/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1029 [16.0][MIG] account_banking_sepa_direct_debit: Migration to 16.0
  account_banking_sepa_direct_debit/README.rst
  account_banking_sepa_direct_debit/__init__.py
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/data/account_payment_method.xml
  account_banking_sepa_direct_debit/data/mandate_expire_cron.xml
  account_banking_sepa_direct_debit/data/pain.008.001.02.xsd
  account_banking_sepa_direct_debit/data/pain.008.001.03.xsd
  account_banking_sepa_direct_debit/data/pain.008.001.04.xsd
  account_banking_sepa_direct_debit/data/pain.008.003.02.xsd
  account_banking_sepa_direct_debit/data/report_paperformat.xml
  account_banking_sepa_direct_debit/demo/sepa_direct_debit_demo.xml
  account_banking_sepa_direct_debit/i18n/account_banking_sepa_direct_debit.pot
  account_banking_sepa_direct_debit/i18n/de.po
  account_banking_sepa_direct_debit/i18n/es.po
  account_banking_sepa_direct_debit/i18n/es_AR.po
  account_banking_sepa_direct_debit/i18n/fr.po
  account_banking_sepa_direct_debit/i18n/hr.po
  account_banking_sepa_direct_debit/i18n/it.po
  account_banking_sepa_direct_debit/i18n/nb_NO.po
  account_banking_sepa_direct_debit/i18n/nl.po
  account_banking_sepa_direct_debit/i18n/pt_BR.po
  account_banking_sepa_direct_debit/i18n/sl.po
  account_banking_sepa_direct_debit/models/__init__.py
  account_banking_sepa_direct_debit/models/account_banking_mandate.py
  account_banking_sepa_direct_debit/models/account_payment_line.py
  account_banking_sepa_direct_debit/models/account_payment_method.py
  account_banking_sepa_direct_debit/models/account_payment_mode.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_banking_sepa_direct_debit/models/res_company.py
  account_banking_sepa_direct_debit/readme/CONFIGURE.rst
  account_banking_sepa_direct_debit/readme/CONTRIBUTORS.rst
  account_banking_sepa_direct_debit/readme/DESCRIPTION.rst
  account_banking_sepa_direct_debit/readme/INSTALL.rst
  account_banking_sepa_direct_debit/readme/USAGE.rst
  account_banking_sepa_direct_debit/reports/sepa_direct_debit_mandate.xml
  account_banking_sepa_direct_debit/static/description/icon.png
  account_banking_sepa_direct_debit/static/description/icon.svg
  account_banking_sepa_direct_debit/static/description/index.html
  account_banking_sepa_direct_debit/static/src/css/report.css
  account_banking_sepa_direct_debit/tests/__init__.py
  account_banking_sepa_direct_debit/tests/test_mandate.py
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_banking_sepa_direct_debit/views/account_banking_mandate_view.xml
  account_banking_sepa_direct_debit/views/account_payment_mode.xml
  account_banking_sepa_direct_debit/views/report_sepa_direct_debit_mandate.xml
  account_banking_sepa_direct_debit/views/res_config_settings.xml
  account_banking_sepa_direct_debit/wizards/__init__.py
  account_banking_sepa_direct_debit/wizards/res_config_settings.py
  setup/account_banking_sepa_direct_debit/odoo/addons/account_banking_sepa_direct_debit
  setup/account_banking_sepa_direct_debit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#990 [16.0][MIG] account_banking_sepa_credit_transfer: Migration to 16.0
  account_banking_sepa_credit_transfer/README.rst
  account_banking_sepa_credit_transfer/__init__.py
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/data/account_payment_method.xml
  account_banking_sepa_credit_transfer/data/pain.001.001.02.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.03.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.04.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.05.xsd
  account_banking_sepa_credit_transfer/data/pain.001.003.03.xsd
  account_banking_sepa_credit_transfer/demo/sepa_credit_transfer_demo.xml
  account_banking_sepa_credit_transfer/i18n/account_banking_sepa_credit_transfer.pot
  account_banking_sepa_credit_transfer/i18n/ca.po
  account_banking_sepa_credit_transfer/i18n/de.po
  account_banking_sepa_credit_transfer/i18n/es.po
  account_banking_sepa_credit_transfer/i18n/es_AR.po
  account_banking_sepa_credit_transfer/i18n/fr.po
  account_banking_sepa_credit_transfer/i18n/fr_FR.po
  account_banking_sepa_credit_transfer/i18n/hr.po
  account_banking_sepa_credit_transfer/i18n/nb_NO.po
  account_banking_sepa_credit_transfer/i18n/nl.po
  account_banking_sepa_credit_transfer/i18n/pt_BR.po
  account_banking_sepa_credit_transfer/i18n/sl.po
  account_banking_sepa_credit_transfer/i18n/sv.po
  account_banking_sepa_credit_transfer/models/__init__.py
  account_banking_sepa_credit_transfer/models/account_payment_line.py
  account_banking_sepa_credit_transfer/models/account_payment_method.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/readme/CONFIGURE.rst
  account_banking_sepa_credit_transfer/readme/CONTRIBUTORS.rst
  account_banking_sepa_credit_transfer/readme/CREDITS.rst
  account_banking_sepa_credit_transfer/readme/DESCRIPTION.rst
  account_banking_sepa_credit_transfer/readme/INSTALL.rst
  account_banking_sepa_credit_transfer/readme/USAGE.rst
  account_banking_sepa_credit_transfer/static/description/icon.png
  account_banking_sepa_credit_transfer/static/description/icon.svg
  account_banking_sepa_credit_transfer/static/description/index.html
  account_banking_sepa_credit_transfer/tests/__init__.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  setup/account_banking_sepa_credit_transfer/odoo/addons/account_banking_sepa_credit_transfer
  setup/account_banking_sepa_credit_transfer/setup.py
Labels: bot is merging ⏳

#1049 [14.0] account_payment_order: Fix grouped partial reconcile
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: bot is merging ⏳

#1093 [16.0][FIX] account_payment_mode: filter out unique payment methods
  account_payment_mode/models/account_journal.py
Labels: approved, bot is merging ⏳

#1097 [15.0][FIX] account_payment_mode: filter out unique payment methods in _default_inbound_payment_methods()
  account_payment_mode/models/account_journal.py
Labels: approved, bot is merging ⏳

#1095 [16.0][MIG] account_payment_order_notification: Migration to version 16.0
  account_payment_order_notification/README.rst
  account_payment_order_notification/__init__.py
  account_payment_order_notification/__manifest__.py
  account_payment_order_notification/data/mail_template_data.xml
  account_payment_order_notification/i18n/account_payment_order_notification.pot
  account_payment_order_notification/i18n/es.po
  account_payment_order_notification/models/__init__.py
  account_payment_order_notification/models/account_payment_order.py
  account_payment_order_notification/models/account_payment_order_notification.py
  account_payment_order_notification/readme/CONFIGURE.rst
  account_payment_order_notification/readme/CONTRIBUTORS.rst
  account_payment_order_notification/readme/DESCRIPTION.rst
  account_payment_order_notification/readme/USAGE.rst
  account_payment_order_notification/security/ir.model.access.csv
  account_payment_order_notification/static/description/icon.png
  account_payment_order_notification/static/description/index.html
  account_payment_order_notification/tests/__init__.py
  account_payment_order_notification/tests/test_account_payment_order_notification.py
  account_payment_order_notification/views/account_payment_order_notification_view.xml
  account_payment_order_notification/views/account_payment_order_view.xml
  account_payment_order_notification/wizard/__init__.py
  account_payment_order_notification/wizard/wizard_account_payment_order_notification.py
  account_payment_order_notification/wizard/wizard_account_payment_order_notification_views.xml
  setup/account_payment_order_notification/odoo/addons/account_payment_order_notification
  setup/account_payment_order_notification/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1101 [14.0][IMP] account_payment_order_grouped_output: Don't generate grouped move when 1 line
  account_payment_order_grouped_output/models/account_payment_order.py
  account_payment_order_grouped_output/tests/test_payment_order_inbound_grouped.py
Labels: approved, bot is merging ⏳

#1092 [16.0][FIX] account_payment_mode: increase note field size
  account_payment_mode/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳
