Repository OCA/bank-payment, pull requests merged in 2023-04, with the labels that each got.

#1058 [15.0][MIG]account_payment_order_return:Migration to 15.0
  account_payment_order_return/README.rst
  account_payment_order_return/__init__.py
  account_payment_order_return/__manifest__.py
  account_payment_order_return/i18n/account_payment_order_return.pot
  account_payment_order_return/i18n/ca.po
  account_payment_order_return/i18n/ca_ES.po
  account_payment_order_return/i18n/de.po
  account_payment_order_return/i18n/es.po
  account_payment_order_return/i18n/es_AR.po
  account_payment_order_return/i18n/fr.po
  account_payment_order_return/i18n/fr_FR.po
  account_payment_order_return/readme/CONTRIBUTORS.rst
  account_payment_order_return/readme/DESCRIPTION.rst
  account_payment_order_return/readme/INSTALL.rst
  account_payment_order_return/readme/USAGE.rst
  account_payment_order_return/static/description/icon.png
  account_payment_order_return/static/description/index.html
  account_payment_order_return/tests/__init__.py
  account_payment_order_return/tests/test_account_payment_order_return.py
  account_payment_order_return/wizards/__init__.py
  account_payment_order_return/wizards/account_payment_line_create.py
  account_payment_order_return/wizards/account_payment_line_create_view.xml
  setup/account_payment_order_return/odoo/addons/account_payment_order_return
  setup/account_payment_order_return/setup.py
Labels: bot is merging ⏳

#1066 [15.0][FIX] account_banking_sepa_direct_debit: CSS styling not applied in reports.
  account_banking_sepa_direct_debit/__manifest__.py
Labels: approved, bot is merging ⏳

#1069 [14.0][FIX] account_payment_partner: test integration failure
  account_payment_partner/tests/test_account_payment_partner.py
Labels: approved, bot is merging ⏳

#1070 [16.0][FIX] account_payment_order: create lines with same sequence name
  account_payment_order/models/account_payment_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1040 [14.0] [IMP] Gather all the UserError as one when validating payments in payment order
  account_payment_order/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#1073 [15.0][IMP] account_payment_order: Concatenate all UserError messages
  account_payment_order/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#1074 [16.0][IMP] account_payment_order: Concatenate all UserError messages
  account_payment_order/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#1072 [16.0][FIX] account_payment_partner: bad application of attributes on the field partner_bank_id
  account_payment_partner/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1078 [FIX] account_banking_mandate is not overriding the create method in batch
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/models/account_move.py
Labels: bot is merging ⏳
