Repository OCA/bank-payment, pull requests merged in 2023-07, with the labels that each got.

#1111 [FIX] account_banking_sepa_credit_transfer: required bank account
  account_banking_sepa_credit_transfer/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#1117 Revert "[FIX] account_banking_sepa_credit_transfer: required bank acc…
  account_banking_sepa_credit_transfer/models/account_payment_order.py
Labels: bot is merging ⏳

#1118 [15.0][IMP] account_payment_order: Add a custom message if the invoice does not have a payment method.
  account_payment_order/models/account_move.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#1119 [16.0][IMP] account_payment_order: Add a custom message if the invoice does not have a payment method.
  account_payment_order/models/account_move.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#1102 [15.0][IMP] account_payment_order_grouped_output: Don't generate grouped move when 1 line
  account_payment_order_grouped_output/models/account_payment_order.py
  account_payment_order_grouped_output/tests/test_payment_order_inbound_grouped.py
Labels: approved, bot is merging ⏳

#1122 [16.0][IMP] account_payment_order_grouped_output: Don't generate grouped move when 1 line
  account_payment_order_grouped_output/models/account_payment_order.py
  account_payment_order_grouped_output/tests/test_payment_order_inbound_grouped.py
Labels: bot is merging ⏳

#1121 [14.0][FIX] account_payment_order: incorrect inbound partial reconciliations
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_inbound.py
Labels: approved, bot is merging ⏳

#1126 [16.0][FIX] account_banking_sepa_direct_debit: Avoid singleton error
  account_banking_sepa_direct_debit/models/account_banking_mandate.py
Labels: approved, bot is merging ⏳

#1113 [14.0][FIX]account_payment_order_notification: Email template fix
  account_payment_order_notification/data/mail_template_data.xml
  account_payment_order_notification/i18n/es.po
  account_payment_order_notification/i18n/fr.po
Labels: approved, ready to merge, bot is merging ⏳

#1127 [15.0][FW] account_payment_order: Fix grouped partial reconcile + incorrect inbound partial reconciliations
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: bot is merging ⏳
