Repository OCA/bank-payment, pull requests merged in 2023-03, with the labels that each got.

#1052 [16.0] account_payment_mode: add "sequence" field on account.payment.mode
  account_payment_mode/models/account_payment_mode.py
  account_payment_mode/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳

#1053 [15.0] account_payment_order: missing commits
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/es.po
  account_payment_order/models/account_move.py
  account_payment_order/models/account_move_line.py
  account_payment_order/readme/CONTRIBUTORS.rst
  account_payment_order/report/account_payment_order.xml
  account_payment_order/tests/test_payment_order_outbound.py
Labels: bot is merging ⏳

#1054 [15.0][REF] account_payment_*: Use native payment object
  account_banking_mandate/__manifest__.py
  account_banking_mandate/models/__init__.py
  account_banking_mandate/models/bank_payment_line.py
  account_banking_mandate/tests/test_invoice_mandate.py
  account_banking_mandate/views/bank_payment_line_view.xml
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/models/__init__.py
  account_banking_pain_base/models/account_payment_line.py
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/models/bank_payment_line.py
  account_banking_pain_base/views/bank_payment_line_view.xml
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/models/__init__.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_banking_sepa_direct_debit/models/bank_payment_line.py
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_payment_order/__manifest__.py
  account_payment_order/data/payment_seq.xml
  account_payment_order/migrations/14.0.1.3.0/pre-migration.py
  account_payment_order/migrations/15.0.2.0.0/post-migration.py
  account_payment_order/models/__init__.py
  account_payment_order/models/account_move_line.py
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/models/account_payment_mode.py
  account_payment_order/models/account_payment_order.py
  account_payment_order/models/bank_payment_line.py
  account_payment_order/security/ir.model.access.csv
  account_payment_order/security/payment_security.xml
  account_payment_order/tests/test_account_payment.py
  account_payment_order/tests/test_payment_mode.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_move_line.xml
  account_payment_order/views/account_payment_line.xml
  account_payment_order/views/account_payment_mode.xml
  account_payment_order/views/account_payment_order.xml
  account_payment_order/views/bank_payment_line.xml
Labels: bot is merging ⏳

#1055 [15.0][MIG] account_payment_order_grouped_output: Migration to 15.0
  account_payment_order_grouped_output/README.rst
  account_payment_order_grouped_output/__init__.py
  account_payment_order_grouped_output/__manifest__.py
  account_payment_order_grouped_output/models/__init__.py
  account_payment_order_grouped_output/models/account_move.py
  account_payment_order_grouped_output/models/account_payment_mode.py
  account_payment_order_grouped_output/models/account_payment_order.py
  account_payment_order_grouped_output/readme/DESCRIPTION.rst
  account_payment_order_grouped_output/static/description/index.html
  account_payment_order_grouped_output/tests/__init__.py
  account_payment_order_grouped_output/tests/test_payment_order_inbound_grouped.py
  account_payment_order_grouped_output/views/account_payment_mode_views.xml
  account_payment_order_grouped_output/views/account_payment_order_views.xml
  setup/account_payment_order_grouped_output/odoo/addons/account_payment_order_grouped_output
  setup/account_payment_order_grouped_output/setup.py
Labels: bot is merging ⏳

#1044 [16.0][MIG] account_payment_order_grouped_output: 16.0
  account_payment_order_grouped_output/README.rst
  account_payment_order_grouped_output/__init__.py
  account_payment_order_grouped_output/__manifest__.py
  account_payment_order_grouped_output/i18n/account_payment_order_grouped_output.pot
  account_payment_order_grouped_output/models/__init__.py
  account_payment_order_grouped_output/models/account_move.py
  account_payment_order_grouped_output/models/account_payment_mode.py
  account_payment_order_grouped_output/models/account_payment_order.py
  account_payment_order_grouped_output/readme/DESCRIPTION.rst
  account_payment_order_grouped_output/static/description/icon.png
  account_payment_order_grouped_output/static/description/index.html
  account_payment_order_grouped_output/tests/__init__.py
  account_payment_order_grouped_output/tests/test_payment_order_inbound_grouped.py
  account_payment_order_grouped_output/views/account_payment_mode_views.xml
  account_payment_order_grouped_output/views/account_payment_order_views.xml
  setup/account_payment_order_grouped_output/odoo/addons/account_payment_order_grouped_output
  setup/account_payment_order_grouped_output/setup.py
Labels: bot is merging ⏳

#820 [14.0] account_payment_sale: add payment_mode_id in sale.report
  account_payment_sale/models/__init__.py
  account_payment_sale/models/sale_report.py
Labels: approved, bot is merging ⏳

#893 [13.0][IMP] account_payment_order - Split method create_account_payment_line for better inheritability
  account_payment_order/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1064 [15.0] [FIX] account_payment_order: Update list of IBAN codes.
  account_banking_pain_base/models/account_payment_order.py
Labels: approved, bot is merging ⏳
