Repository OCA/bank-payment, pull requests merged in 2023-02, with the labels that each got.

#1015 [14.0][ADD] account_payment_order_grouped_output: Generate grouped entries from payment orders + [FIX] account_payment_order: Remove leftover options
  account_payment_order/models/account_payment_mode.py
  account_payment_order/tests/test_payment_mode.py
  account_payment_order/views/account_payment_mode.xml
  account_payment_order_grouped_output/README.rst
  account_payment_order_grouped_output/__init__.py
  account_payment_order_grouped_output/__manifest__.py
  account_payment_order_grouped_output/models/__init__.py
  account_payment_order_grouped_output/models/account_move.py
  account_payment_order_grouped_output/models/account_payment_mode.py
  account_payment_order_grouped_output/models/account_payment_order.py
  account_payment_order_grouped_output/readme/DESCRIPTION.rst
  account_payment_order_grouped_output/static/description/index.html
  account_payment_order_grouped_output/tests/__init__.py
  account_payment_order_grouped_output/tests/test_payment_order_inbound_grouped.py
  account_payment_order_grouped_output/views/account_payment_mode_views.xml
  account_payment_order_grouped_output/views/account_payment_order_views.xml
  setup/account_payment_order_grouped_output/odoo/addons/account_payment_order_grouped_output
  setup/account_payment_order_grouped_output/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1025 [14.0] [FIX] account_payment_order: Update list of IBAN codes.
  account_banking_pain_base/models/account_payment_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1022 [14.0] account_payment_order: Add pre_init_hook to add computed columns
  account_payment_order/__init__.py
  account_payment_order/__manifest__.py
  account_payment_order/hooks.py
Labels: approved, bot is merging ⏳

#1031 [15.0][FIX] account_banking_sepa_*: Remove post-installs
  account_banking_sepa_credit_transfer/__init__.py
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/post_install.py
  account_banking_sepa_direct_debit/__init__.py
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/post_install.py
Labels: approved, bot is merging ⏳

#1021 [14.0] account_payment_partner: Add pre_init_hook to add computed columns
  account_payment_partner/__init__.py
  account_payment_partner/__manifest__.py
  account_payment_partner/hooks.py
Labels: approved, bot is merging ⏳

#1047 [15.0] account_payment_order: Add pre_init_hook to add computed column
  account_payment_order/__init__.py
  account_payment_order/__manifest__.py
  account_payment_order/hooks.py
Labels: bot is merging ⏳

#1045 [14.0][FIX] account_payment_order_notification: Show supplier invoice reference if applicable.
  account_payment_order_notification/data/mail_template_data.xml
  account_payment_order_notification/i18n/account_payment_order_notification.pot
  account_payment_order_notification/i18n/es.po
  account_payment_order_notification/migrations/14.0.1.2.0/noupdate_changes.xml
  account_payment_order_notification/migrations/14.0.1.2.0/post-migration.py
Labels: approved, bot is merging ⏳

#1046 [15.0] account_payment_partner: Add pre_init_hook to add computed columns
  account_payment_partner/__init__.py
  account_payment_partner/__manifest__.py
  account_payment_partner/hooks.py
Labels: bot is merging ⏳

#1048 [16.0] account_payment_partner: Add pre_init_hook to add computed columns
  account_payment_partner/__init__.py
  account_payment_partner/__manifest__.py
  account_payment_partner/hooks.py
Labels: bot is merging ⏳

#1051 [14.0][IMP] account_payment_order_notification: Set format_date() to show date from template record
  account_payment_order_notification/data/mail_template_data.xml
Labels: approved, bot is merging ⏳
