Repository OCA/bank-payment, pull requests merged in 2023-11, with the labels that each got.

#1149 [16.0] Add warning when payment order is not SEPA
  account_banking_pain_base/models/account_payment_method.py
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/views/account_payment_method.xml
  account_banking_pain_base/views/account_payment_order.xml
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/data/account_payment_method.xml
  account_banking_sepa_credit_transfer/migrations/16.0.1.0.1/post-migration.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/data/account_payment_method.xml
  account_banking_sepa_direct_debit/migrations/16.0.1.0.2/post-migration.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/views/account_payment_line.xml
Labels: approved, bot is merging ⏳

#1163 [IMP] grouped invoices: " - ".join in stead of "-".join
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_payment_order/models/account_payment_line.py
Labels: bot is merging ⏳

#1165 [15.0][IMP]grouped invoices: " - ".join in stead of "-".join
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_payment_order/models/account_payment_line.py
Labels: bot is merging ⏳

#1166 [16.0][IMP]grouped invoices: " - ".join in stead of "-".join
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_payment_order/models/account_payment_line.py
Labels: bot is merging ⏳

#1164 [FIX]payment order - fix compute_partner_bank_id
  account_payment_order/models/account_move_line.py
Labels: bot is merging ⏳

#1172 [16.0][IMP] account_payment_order: add payment lines smart button on invoice
  account_payment_order/models/account_move.py
  account_payment_order/views/account_invoice_view.xml
  account_payment_order/views/account_payment_line.xml
Labels: approved, bot is merging ⏳

#1167 [16.0] account_payment_purchase: replace api.onchange by computed field on purchase.order
  account_payment_purchase/models/purchase_order.py
  account_payment_purchase/tests/test_account_payment_purchase.py
  account_payment_purchase/views/purchase_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1176 [16.0][FIX] account_payment_order: Restrict payment lines button to payment group
  account_payment_order/views/account_invoice_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1182 [17.0] [MIG] account_payment_mode
  account_payment_mode/README.rst
  account_payment_mode/__init__.py
  account_payment_mode/__manifest__.py
  account_payment_mode/demo/payment_demo.xml
  account_payment_mode/i18n/account_payment_mode.pot
  account_payment_mode/i18n/am.po
  account_payment_mode/i18n/ca.po
  account_payment_mode/i18n/da_DK.po
  account_payment_mode/i18n/de.po
  account_payment_mode/i18n/el_GR.po
  account_payment_mode/i18n/es.po
  account_payment_mode/i18n/es_AR.po
  account_payment_mode/i18n/es_CL.po
  account_payment_mode/i18n/es_ES.po
  account_payment_mode/i18n/fi.po
  account_payment_mode/i18n/fr.po
  account_payment_mode/i18n/fr_FR.po
  account_payment_mode/i18n/gl.po
  account_payment_mode/i18n/hr.po
  account_payment_mode/i18n/it.po
  account_payment_mode/i18n/nb_NO.po
  account_payment_mode/i18n/nl.po
  account_payment_mode/i18n/pt.po
  account_payment_mode/i18n/pt_BR.po
  account_payment_mode/i18n/pt_PT.po
  account_payment_mode/i18n/sl.po
  account_payment_mode/i18n/sv.po
  account_payment_mode/i18n/sv_SE.po
  account_payment_mode/i18n/tr.po
  account_payment_mode/i18n/zh_CN.po
  account_payment_mode/models/__init__.py
  account_payment_mode/models/account_journal.py
  account_payment_mode/models/account_payment_method.py
  account_payment_mode/models/account_payment_mode.py
  account_payment_mode/pyproject.toml
  account_payment_mode/readme/CONFIGURE.md
  account_payment_mode/readme/CONTRIBUTORS.md
  account_payment_mode/readme/DESCRIPTION.md
  account_payment_mode/readme/USAGE.md
  account_payment_mode/security/account_payment_mode.xml
  account_payment_mode/security/ir.model.access.csv
  account_payment_mode/static/description/icon.png
  account_payment_mode/static/description/index.html
  account_payment_mode/tests/__init__.py
  account_payment_mode/tests/test_account_payment_mode.py
  account_payment_mode/views/account_journal.xml
  account_payment_mode/views/account_payment_method.xml
  account_payment_mode/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳

#1183 [17.0] [MIG] account_payment_partner
  account_payment_partner/README.rst
  account_payment_partner/__init__.py
  account_payment_partner/__manifest__.py
  account_payment_partner/demo/partner_demo.xml
  account_payment_partner/hooks.py
  account_payment_partner/i18n/account_payment_partner.pot
  account_payment_partner/i18n/ca.po
  account_payment_partner/i18n/da_DK.po
  account_payment_partner/i18n/de.po
  account_payment_partner/i18n/es.po
  account_payment_partner/i18n/es_AR.po
  account_payment_partner/i18n/es_CL.po
  account_payment_partner/i18n/fr.po
  account_payment_partner/i18n/fr_FR.po
  account_payment_partner/i18n/hr.po
  account_payment_partner/i18n/it.po
  account_payment_partner/i18n/nb_NO.po
  account_payment_partner/i18n/nl.po
  account_payment_partner/i18n/pt.po
  account_payment_partner/i18n/pt_BR.po
  account_payment_partner/i18n/sl.po
  account_payment_partner/i18n/sv.po
  account_payment_partner/models/__init__.py
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_move_line.py
  account_payment_partner/models/account_payment_mode.py
  account_payment_partner/models/res_partner.py
  account_payment_partner/pyproject.toml
  account_payment_partner/readme/CONTRIBUTORS.md
  account_payment_partner/readme/DESCRIPTION.md
  account_payment_partner/readme/HISTORY.md
  account_payment_partner/readme/USAGE.md
  account_payment_partner/reports/__init__.py
  account_payment_partner/reports/account_invoice_report.py
  account_payment_partner/reports/account_invoice_report_view.xml
  account_payment_partner/static/description/icon.png
  account_payment_partner/static/description/index.html
  account_payment_partner/tests/__init__.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_move_line.xml
  account_payment_partner/views/account_move_view.xml
  account_payment_partner/views/account_payment_mode.xml
  account_payment_partner/views/report_invoice.xml
  account_payment_partner/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1120 [14.0][FIX] account_payment_purchase: use company context on partner lookup
  account_payment_purchase/__manifest__.py
  account_payment_purchase/models/purchase_order.py
Labels: bot is merging ⏳, stale

#1188 [16.0][FIX] account_payment_order: Always return a string in the _get_payment_order_order_communication_direct() method.
  account_payment_order/models/account_move.py
  account_payment_order/tests/test_account_payment.py
  account_payment_order/tests/test_payment_mode.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#1143 [14.0][IMP] account_banking_mandate: Allow to set a specific mandate reference or sequence
  account_banking_mandate/data/mandate_reference_sequence.xml
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/models/account_move.py
  account_banking_mandate/tests/test_mandate.py
  account_banking_mandate/views/account_banking_mandate_view.xml
Labels: bot is merging ⏳

#1190 [16.0][IMP] account_banking_mandate: Allow to set a specific mandate reference or sequence + multi-company compatibility
  account_banking_mandate/data/mandate_reference_sequence.xml
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/tests/test_mandate.py
  account_banking_mandate/views/account_banking_mandate_view.xml
Labels: approved, bot is merging ⏳

#1189 [15.0][IMP] account_banking_mandate: Allow to set a specific mandate reference or sequence + multi-company compatibility + model_create_multi
  account_banking_mandate/data/mandate_reference_sequence.xml
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/models/account_move.py
  account_banking_mandate/tests/test_mandate.py
  account_banking_mandate/views/account_banking_mandate_view.xml
Labels: approved, bot is merging ⏳
