Repository OCA/bank-payment, pull requests merged in 2024-11, with the labels that each got.

#1161 [16.0][MIG] account_payment_order_tier_validation: Migration to 16.0
  account_payment_order_tier_validation/README.rst
  account_payment_order_tier_validation/__init__.py
  account_payment_order_tier_validation/__manifest__.py
  account_payment_order_tier_validation/i18n/account_payment_order_tier_validation.pot
  account_payment_order_tier_validation/i18n/pt_BR.po
  account_payment_order_tier_validation/models/__init__.py
  account_payment_order_tier_validation/models/account_payment_order.py
  account_payment_order_tier_validation/models/tier_definition.py
  account_payment_order_tier_validation/readme/CONFIGURE.rst
  account_payment_order_tier_validation/readme/CONTRIBUTORS.rst
  account_payment_order_tier_validation/readme/DESCRIPTION.rst
  account_payment_order_tier_validation/readme/INSTALL.rst
  account_payment_order_tier_validation/readme/USAGE.rst
  account_payment_order_tier_validation/static/description/icon.png
  account_payment_order_tier_validation/static/description/index.html
  account_payment_order_tier_validation/tests/__init__.py
  account_payment_order_tier_validation/tests/test_payment_order_tier_validation.py
  account_payment_order_tier_validation/views/account_payment_order.xml
  setup/account_payment_order_tier_validation/odoo/addons/account_payment_order_tier_validation
  setup/account_payment_order_tier_validation/setup.py
Labels: approved, bot is merging ⏳, stale

#1375 [15.0][IMP] account_banking_mandate: Allow to change the bank mandate on invoices if they are not paid.
  account_banking_mandate/models/account_move.py
  account_banking_mandate/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1377 [17.0][FIX] account_payment_partner: Fix tests compatibility (hr_expense + partner_multi_company)
  account_payment_partner/tests/test_account_payment_partner.py
Labels: bot is merging ⏳

#1378 [17.0][FIX] account_payment_order: add missing company currency field on payment line
  account_payment_order/views/account_payment_line.xml
Labels: approved, bot is merging ⏳

#1237 [15.0][FIX] account_payment_order: Filter bank on company
  account_payment_order/models/account_move_line.py
  account_payment_order/models/account_payment_line.py
Labels: bot is merging ⏳, stale

#1380 [17.0][FIX] account_payment_order: fix ``TypeError``
  account_payment_order/models/account_move.py
Labels: approved, bot is merging ⏳
