Repository OCA/bank-payment, pull requests merged in 2024-04, with the labels that each got.

#1244 [16.0][IMP] account_banking_sepa_direct_debit: Button send mandate per email
  account_banking_sepa_direct_debit/README.rst
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/data/mail_template_data.xml
  account_banking_sepa_direct_debit/i18n/account_banking_sepa_direct_debit.pot
  account_banking_sepa_direct_debit/i18n/es.po
  account_banking_sepa_direct_debit/models/__init__.py
  account_banking_sepa_direct_debit/models/account_banking_mandate.py
  account_banking_sepa_direct_debit/models/mail_compose_message.py
  account_banking_sepa_direct_debit/readme/CONTRIBUTORS.rst
  account_banking_sepa_direct_debit/static/description/index.html
  account_banking_sepa_direct_debit/tests/test_mandate.py
  account_banking_sepa_direct_debit/views/account_banking_mandate_view.xml
Labels: approved, ready to merge, merged 🎉

#1246 [IMP] account_payment_sale: Add payment mode in invoicing grouping criteria
  account_payment_sale/models/sale_order.py
  account_payment_sale/tests/test_sale_order.py
Labels: approved, bot is merging ⏳

#1249 [14.0][FIX] account_payment_order: exclude cancel journal entries
  account_payment_order/wizard/account_payment_line_create.py
Labels: approved, bot is merging ⏳

#1248 [FIX][17.0] account_payment_order: Fix dynamic domain
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/wizard/account_payment_line_create.py
  account_payment_order/wizard/account_payment_line_create_view.xml
Labels: bot is merging ⏳

#1187 [17.0][MIG] account_payment_purchase_stock: Migration to 17.0
  account_payment_purchase_stock/README.rst
  account_payment_purchase_stock/__init__.py
  account_payment_purchase_stock/__manifest__.py
  account_payment_purchase_stock/i18n/account_payment_purchase_stock.pot
  account_payment_purchase_stock/i18n/es.po
  account_payment_purchase_stock/i18n/es_AR.po
  account_payment_purchase_stock/i18n/fr.po
  account_payment_purchase_stock/i18n/fr_FR.po
  account_payment_purchase_stock/i18n/it.po
  account_payment_purchase_stock/models/__init__.py
  account_payment_purchase_stock/models/stock_rule.py
  account_payment_purchase_stock/pyproject.toml
  account_payment_purchase_stock/readme/CONTRIBUTORS.md
  account_payment_purchase_stock/readme/DESCRIPTION.md
  account_payment_purchase_stock/readme/INSTALL.md
  account_payment_purchase_stock/readme/USAGE.md
  account_payment_purchase_stock/static/description/icon.png
  account_payment_purchase_stock/static/description/index.html
  account_payment_purchase_stock/tests/__init__.py
  account_payment_purchase_stock/tests/test_account_payment_purchase_stock.py
Labels: approved, ready to merge, bot is merging ⏳

#1251 [16.0][MIG] account_payment_order_transfer_journal
  account_banking_pain_base/views/res_config_settings.xml
  account_banking_sepa_direct_debit/views/res_config_settings.xml
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/models/__init__.py
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/models/account_payment_mode.py
  account_payment_order/models/res_company.py
  account_payment_order/readme/CONTRIBUTORS.rst
  account_payment_order/readme/USAGE.rst
  account_payment_order/static/description/index.html
  account_payment_order/tests/__init__.py
  account_payment_order/tests/test_payment_order_transfer_journal.py
  account_payment_order/views/account_payment_mode.xml
  account_payment_order/wizard/__init__.py
  account_payment_order/wizard/res_config_settings.py
  account_payment_order/wizard/res_config_settings.xml
Labels: approved, bot is merging ⏳

#1170 [16.0][IMP] account_payment_order: update payment reference on open payment order
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/models/account_payment.py
  account_payment_order/security/ir.model.access.csv
  account_payment_order/static/description/index.html
  account_payment_order/views/account_payment_views.xml
  account_payment_order/wizard/__init__.py
  account_payment_order/wizard/account_payment_update.py
  account_payment_order/wizard/account_payment_update_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1252 [16.0][FIX] account_payment_partner: payment mode compute
  account_payment_partner/models/account_move.py
Labels: approved, bot is merging ⏳

#1254 [16.0][FIX] account_payment_method_fs_storage: Translated term
  account_payment_method_fs_storage/i18n/es.po
Labels: bot is merging ⏳

#1148 [16.0][IMP] account_payment_order: adds restriction for duplicated move lines in payment order
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#1256 [17.0][FIX] account_banking_mandate: change name_get method to use _compute…
  account_banking_mandate/models/account_banking_mandate.py
Labels: bot is merging ⏳
