Repository OCA/bank-payment, pull requests merged in 2024-05, with the labels that each got.

#1215 [16.0][FIX] account_payment_order_notification: Set rec_name for payment order notification
  account_payment_order_notification/models/account_payment_order_notification.py
Labels: approved, ready to merge, bot is merging ⏳

#1258 [IMP] account_banking_sepa_direct_debit: increase report signature space
  account_banking_sepa_direct_debit/views/report_sepa_direct_debit_mandate.xml
Labels: approved, ready to merge, bot is merging ⏳

#1263 [15.0][IMP] account_banking_sepa_direct_debit: increase report signature space
  account_banking_sepa_direct_debit/views/report_sepa_direct_debit_mandate.xml
Labels: approved, bot is merging ⏳

#1264 [16.0][IMP] account_banking_sepa_direct_debit: increase report signature space
  account_banking_sepa_direct_debit/views/report_sepa_direct_debit_mandate.xml
Labels: approved, bot is merging ⏳

#1266 [17.0][FIX] account_banking_sepa_direct_debit: unit tests
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_banking_sepa_direct_debit/tests/test_sdd.py
Labels: bot is merging ⏳

#1265 [17.0][IMP] account_banking_sepa_direct_debit: increase report signature space
  account_banking_sepa_direct_debit/views/report_sepa_direct_debit_mandate.xml
Labels: bot is merging ⏳

#1255 [MIG] account_banking_mandate_sale: migration to 17.0
  account_banking_mandate_sale/README.rst
  account_banking_mandate_sale/__init__.py
  account_banking_mandate_sale/__manifest__.py
  account_banking_mandate_sale/i18n/account_banking_mandate_sale.pot
  account_banking_mandate_sale/i18n/ca.po
  account_banking_mandate_sale/i18n/ca_ES.po
  account_banking_mandate_sale/i18n/de.po
  account_banking_mandate_sale/i18n/es.po
  account_banking_mandate_sale/i18n/hr.po
  account_banking_mandate_sale/i18n/nl.po
  account_banking_mandate_sale/i18n/nl_NL.po
  account_banking_mandate_sale/i18n/pt_BR.po
  account_banking_mandate_sale/i18n/sl.po
  account_banking_mandate_sale/models/__init__.py
  account_banking_mandate_sale/models/sale_order.py
  account_banking_mandate_sale/pyproject.toml
  account_banking_mandate_sale/readme/CONTRIBUTORS.md
  account_banking_mandate_sale/readme/DESCRIPTION.md
  account_banking_mandate_sale/readme/USAGE.md
  account_banking_mandate_sale/static/description/icon.png
  account_banking_mandate_sale/static/description/index.html
  account_banking_mandate_sale/views/sale_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#1253 [14.0][ADD] account_payment_order_lock_draft
  account_payment_order_lock_draft/README.rst
  account_payment_order_lock_draft/__init__.py
  account_payment_order_lock_draft/__manifest__.py
  account_payment_order_lock_draft/models/__init__.py
  account_payment_order_lock_draft/models/account_move.py
  account_payment_order_lock_draft/readme/CONTRIBUTORS.rst
  account_payment_order_lock_draft/readme/DESCRIPTION.rst
  account_payment_order_lock_draft/static/description/icon.png
  account_payment_order_lock_draft/static/description/index.html
  account_payment_order_lock_draft/tests/__init__.py
  account_payment_order_lock_draft/tests/test_account_payment_order_lock_draft.py
  setup/account_payment_order_lock_draft/odoo/addons/account_payment_order_lock_draft
  setup/account_payment_order_lock_draft/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1259 [15.0][IMP] account_banking_mandate_contact: Improve tests (remove mock)
  account_banking_mandate/models/account_payment_method.py
  account_banking_mandate_contact/tests/test_account_payment_order.py
Labels: bot is merging ⏳

#1269 [16.0][IMP] account_payment_sale: Improve tests to prevent error with pricelist_id field
  account_payment_sale/tests/test_sale_order.py
Labels: bot is merging ⏳

#1144 Fix mandates tree view in res.partner.bank for better ergonomy
  account_banking_mandate/views/res_partner_bank_view.xml
Labels: approved, bot is merging ⏳, stale

#932 [10.0][IMP] account_banking_pain_base: Allow overriding initiating pa…
  account_banking_pain_base/models/account_payment_order.py
Labels: approved, ready to merge, bot is merging ⏳, no stale

#1272 [16.0][IMP] account_banking_mandate_contact: Improve tests (remove mock)
  account_banking_mandate/models/account_payment_method.py
  account_banking_mandate_contact/tests/test_account_payment_order.py
Labels: approved, bot is merging ⏳

#1275 [17.0][FIX] account_payment_partner: DeprecationWarning: XML
  account_payment_partner/static/description/index.html
Labels: bot is merging ⏳

#1247 [15.0][FIX] account_payment_purchase: Leave the partner_bank_id field empty in purchase invoice process
  account_payment_purchase/models/purchase_order.py
  account_payment_purchase/tests/test_account_payment_purchase.py
Labels: approved, bot is merging ⏳

#1274 [17.0][MIG] account_banking_mandate_sale_contact: Migration to 17.0
  account_banking_mandate_sale_contact/README.rst
  account_banking_mandate_sale_contact/__init__.py
  account_banking_mandate_sale_contact/__manifest__.py
  account_banking_mandate_sale_contact/i18n/account_banking_mandate_sale_contact.pot
  account_banking_mandate_sale_contact/i18n/es.po
  account_banking_mandate_sale_contact/i18n/it.po
  account_banking_mandate_sale_contact/models/__init__.py
  account_banking_mandate_sale_contact/models/res_company.py
  account_banking_mandate_sale_contact/models/res_config_settings.py
  account_banking_mandate_sale_contact/models/res_partner.py
  account_banking_mandate_sale_contact/models/sale_order.py
  account_banking_mandate_sale_contact/pyproject.toml
  account_banking_mandate_sale_contact/readme/CONFIGURE.md
  account_banking_mandate_sale_contact/readme/CONTRIBUTORS.md
  account_banking_mandate_sale_contact/readme/DESCRIPTION.md
  account_banking_mandate_sale_contact/readme/USAGE.md
  account_banking_mandate_sale_contact/static/description/icon.png
  account_banking_mandate_sale_contact/static/description/icon.svg
  account_banking_mandate_sale_contact/static/description/index.html
  account_banking_mandate_sale_contact/tests/__init__.py
  account_banking_mandate_sale_contact/tests/test_account_banking_mandate_sale_contact.py
  account_banking_mandate_sale_contact/views/res_config_settings.xml
  account_banking_mandate_sale_contact/views/res_partner.xml
Labels: approved, bot is merging ⏳
