Repository OCA/bank-payment, pull requests merged in 2024-09, with the labels that each got.

#1341 [15.0][IMP] account_payment_order_grouped_output: Maturity date in grouped moves
  account_payment_order_grouped_output/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#1342 [14.0][IMP] account_payment_order_grouped_output: Maturity date in grouped moves
  account_payment_order_grouped_output/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#1345 [17.0] [MIG] account_payment_order_grouped_output
  account_payment_order_grouped_output/README.rst
  account_payment_order_grouped_output/__init__.py
  account_payment_order_grouped_output/__manifest__.py
  account_payment_order_grouped_output/i18n/account_payment_order_grouped_output.pot
  account_payment_order_grouped_output/i18n/es.po
  account_payment_order_grouped_output/i18n/fr.po
  account_payment_order_grouped_output/i18n/hr.po
  account_payment_order_grouped_output/i18n/it.po
  account_payment_order_grouped_output/models/__init__.py
  account_payment_order_grouped_output/models/account_move.py
  account_payment_order_grouped_output/models/account_payment_mode.py
  account_payment_order_grouped_output/models/account_payment_order.py
  account_payment_order_grouped_output/pyproject.toml
  account_payment_order_grouped_output/readme/DESCRIPTION.md
  account_payment_order_grouped_output/static/description/icon.png
  account_payment_order_grouped_output/static/description/index.html
  account_payment_order_grouped_output/tests/__init__.py
  account_payment_order_grouped_output/tests/test_payment_order_inbound_grouped.py
  account_payment_order_grouped_output/tests/test_payment_order_outbound_grouped.py
  account_payment_order_grouped_output/views/account_payment_mode_views.xml
  account_payment_order_grouped_output/views/account_payment_order_views.xml
Labels: approved, bot is merging ⏳

#1333 [IMP] account_payment_order: add button to view business document
  account_payment_order/models/account_payment_line.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_line.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1347 [FIX] account_payment_order: Correct payment date
  account_payment_order/models/account_payment_line.py
Labels: approved, bot is merging ⏳

#1344 [14.0][IMP] Add warning when payment order is not SEPA
  account_banking_pain_base/models/account_payment_method.py
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/static/description/index.html
  account_banking_pain_base/views/account_payment_method.xml
  account_banking_pain_base/views/account_payment_order.xml
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/data/account_payment_method.xml
  account_banking_sepa_credit_transfer/migrations/14.0.2.0.3/post-migration.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/data/account_payment_method.xml
  account_banking_sepa_direct_debit/migrations/14.0.2.1.2/post-migration.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/views/account_payment_line.xml
Labels: approved, bot is merging ⏳

#1346 [16.0][FIX] account_payment_order: Assure partner bank account in payments
  account_payment_order/models/account_payment.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#1348 [17.0][FIX] account_payment_order: Assure partner bank account in payments
  account_payment_order/models/account_payment.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#1354 [17.0][FW] [IMP] account_payment_sale: Add payment mode in invoicing grouping criteria
  .oca/oca-port/blacklist/account_payment_sale.json
  account_payment_sale/models/sale_order.py
  account_payment_sale/tests/test_sale_order.py
Labels: approved, bot is merging ⏳

#1357 [15.0][FW] account_payment_purchase: multiple ports from 14.0
  account_payment_purchase/models/account_move.py
  account_payment_purchase/models/purchase_order.py
  account_payment_purchase/tests/test_account_payment_purchase.py
Labels: bot is merging ⏳

#1356 [17.0][FW] [16.0][FIX] account_payment_partner: payment mode compute
  account_payment_partner/models/account_move.py
Labels: bot is merging ⏳

#1350 [16.0][FW] [15.0][IMP] bank-payment : test performance improvement
  account_banking_mandate/tests/test_invoice_mandate.py
  account_banking_mandate/tests/test_mandate.py
  account_banking_mandate_contact/tests/test_account_payment_order.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_banking_sepa_direct_debit/tests/test_mandate.py
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_payment_mode/tests/test_account_payment_mode.py
  account_payment_order/tests/test_bank.py
  account_payment_order/tests/test_payment_mode.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_sale/tests/common.py
  account_payment_sale/tests/test_sale_order.py
Labels: bot is merging ⏳

#1351 [17.0][FW] [16.0][IMP] bank-payment : test performance improvement
  account_banking_mandate/tests/test_invoice_mandate.py
  account_banking_mandate/tests/test_mandate.py
  account_banking_mandate_contact/tests/test_account_payment_order.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
  account_banking_sepa_direct_debit/tests/test_mandate.py
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_payment_mode/tests/test_account_payment_mode.py
  account_payment_order/tests/test_bank.py
  account_payment_order/tests/test_payment_mode.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_sale/tests/common.py
  account_payment_sale/tests/test_sale_order.py
Labels: bot is merging ⏳
