Repository OCA/bank-payment, pull requests merged in 2024-07, with the labels that each got.

#1303 [17.0][FIX] account_payment_purchase: Leave the partner_bank_id field empty in purchase invoice process
  account_payment_purchase/models/purchase_order.py
  account_payment_purchase/tests/test_account_payment_purchase.py
Labels: approved, bot is merging ⏳

#1285 [17.0][IMP] account_payment_order: Mark invoices in a payment order as in payment
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_payment_order/models/account_move.py
  account_payment_order/tests/test_payment_order_inbound.py
Labels: approved, bot is merging ⏳

#1301 [16.0][IMP] account_payment_order: Apply readonly=True to Payment Date field of transactions
  account_payment_order/views/account_payment_line.xml
Labels: bot is merging ⏳

#1305 [14.0][IMP] account_payment_order: Add Transfer moves dates
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#1304 [16.0][IMP] account_payment_order: Add Transfer moves dates
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳

#1306 [17.0][IMP] account_payment_order: Add Transfer moves dates
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_line.xml
Labels: approved, bot is merging ⏳

#1311 [14.0][IMP] account_payment_order*: Define the correct date in the files that are generated.
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_payment_order/models/account_payment.py
  account_payment_order/tests/test_payment_order_inbound.py
Labels: approved, bot is merging ⏳

#1314 [16.0][FIX] account_payment_order: add missing option "structured" to payment line reference type
  account_payment_order/models/account_move.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/tests/test_payment_order_inbound.py
Labels: approved, bot is merging ⏳

#1316 [14.0][FIX] account_invoice_select_for_payment: select partially-paid invoices
  account_invoice_select_for_payment/views/account_move.xml
Labels: approved, bot is merging ⏳

#1320 [14.0][FIX] account_payment_order: out of index date
  account_payment_order/models/account_payment.py
Labels: bot is merging ⏳

#1292 [17.0] [ADD] account_vendor_bank_account_default
  account_vendor_bank_account_default/README.rst
  account_vendor_bank_account_default/__init__.py
  account_vendor_bank_account_default/__manifest__.py
  account_vendor_bank_account_default/models/__init__.py
  account_vendor_bank_account_default/models/account_move.py
  account_vendor_bank_account_default/models/res_partner.py
  account_vendor_bank_account_default/pyproject.toml
  account_vendor_bank_account_default/readme/CONFIGURE.md
  account_vendor_bank_account_default/readme/CONTRIBUTORS.md
  account_vendor_bank_account_default/readme/DESCRIPTION.md
  account_vendor_bank_account_default/readme/ROADMAP.md
  account_vendor_bank_account_default/readme/USAGE.md
  account_vendor_bank_account_default/static/description/icon.png
  account_vendor_bank_account_default/static/description/icon.svg
  account_vendor_bank_account_default/static/description/index.html
  account_vendor_bank_account_default/tests/__init__.py
  account_vendor_bank_account_default/tests/test_account_vendor_bank_account_default.py
  account_vendor_bank_account_default/views/res_partner_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1294 [17.0] [IMP] account_payment_purchase: let indivual partners have bank accounts in puchase
  account_payment_purchase/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1324 [16.0][IMP] account_banking_mandate: Set sequence when creating a mandate with empty mandate reference
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/tests/test_mandate.py
Labels: approved, bot is merging ⏳

#1326 [17.0][FIX] account_payment_purchase: copy the fields to supplier invoices.
  account_payment_purchase/models/account_move.py
  account_payment_purchase/models/purchase_order.py
Labels: approved, bot is merging ⏳

#1312 [17.0][FIX] account_payment_mode: error when payment mode
  account_payment_mode/models/account_journal.py
Labels: approved, ready to merge, bot is merging ⏳
