Repository OCA/bank-payment, pull requests merged in 2024-08, with the labels that each got.

#1293 [17.0] [ADD] account_vendor_bank_account_default_purchase
  account_vendor_bank_account_default_purchase/README.rst
  account_vendor_bank_account_default_purchase/__init__.py
  account_vendor_bank_account_default_purchase/__manifest__.py
  account_vendor_bank_account_default_purchase/models/__init__.py
  account_vendor_bank_account_default_purchase/models/purchase_order.py
  account_vendor_bank_account_default_purchase/pyproject.toml
  account_vendor_bank_account_default_purchase/readme/CONFIGURE.md
  account_vendor_bank_account_default_purchase/readme/CONTRIBUTORS.md
  account_vendor_bank_account_default_purchase/readme/DESCRIPTION.md
  account_vendor_bank_account_default_purchase/readme/ROADMAP.md
  account_vendor_bank_account_default_purchase/readme/USAGE.md
  account_vendor_bank_account_default_purchase/static/description/icon.png
  account_vendor_bank_account_default_purchase/static/description/icon.svg
  account_vendor_bank_account_default_purchase/static/description/index.html
  account_vendor_bank_account_default_purchase/tests/__init__.py
  account_vendor_bank_account_default_purchase/tests/test_account_vendor_bank_account_default.py
Labels: bot is merging ⏳

#1325 [17.0][IMP] account_banking_mandate: Set sequence when creating a mandate with empty mandate reference
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/tests/test_mandate.py
Labels: bot is merging ⏳

#1329 [16.0][FIX] account_payment_mode: error when payment mode
  account_payment_mode/models/account_journal.py
Labels: approved, bot is merging ⏳

#1319 [17.0][IMP] account_payment_order*: Define the correct date in the files that are generated
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_payment_order/models/account_payment.py
  account_payment_order/tests/test_payment_order_inbound.py
Labels: bot is merging ⏳

#1318 [17.0][FIX] account_payment_order: add missing option "structured" to payment line ref type
  account_payment_order/models/account_move.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/tests/test_payment_order_inbound.py
Labels: approved, bot is merging ⏳

#1331 [16.0][FIX/IMP] account_payment_order: use payment_reference if present for out payments
  account_payment_order/models/account_move.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: needs review, approved, bot is merging ⏳

#1334 [17.0][MIG] account_payment_order_notification: Migration to 17.0
  account_payment_order_notification/README.rst
  account_payment_order_notification/__init__.py
  account_payment_order_notification/__manifest__.py
  account_payment_order_notification/data/mail_template_data.xml
  account_payment_order_notification/i18n/account_payment_order_notification.pot
  account_payment_order_notification/i18n/es.po
  account_payment_order_notification/i18n/fr.po
  account_payment_order_notification/i18n/it.po
  account_payment_order_notification/models/__init__.py
  account_payment_order_notification/models/account_payment_order.py
  account_payment_order_notification/models/account_payment_order_notification.py
  account_payment_order_notification/pyproject.toml
  account_payment_order_notification/readme/CONFIGURE.md
  account_payment_order_notification/readme/CONTRIBUTORS.md
  account_payment_order_notification/readme/DESCRIPTION.md
  account_payment_order_notification/readme/USAGE.md
  account_payment_order_notification/security/ir.model.access.csv
  account_payment_order_notification/static/description/icon.png
  account_payment_order_notification/static/description/index.html
  account_payment_order_notification/tests/__init__.py
  account_payment_order_notification/tests/test_account_payment_order_notification.py
  account_payment_order_notification/views/account_payment_order_notification_view.xml
  account_payment_order_notification/views/account_payment_order_view.xml
  account_payment_order_notification/wizard/__init__.py
  account_payment_order_notification/wizard/wizard_account_payment_order_notification.py
  account_payment_order_notification/wizard/wizard_account_payment_order_notification_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1339 [16.0][FIX] account_payment_order: allow multiple payment lines without move line
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: approved, bot is merging ⏳
