Repository OCA/bank-payment, pull requests merged in 2024-03, with the labels that each got.

#1226 [15.0][IMP] account_payment_order: Display a message with the archived bank accounts
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_order.xml
Labels: approved, bot is merging ⏳

#1227 [16.0][IMP] account_payment_order: Display a message with the archived bank accounts
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_order.xml
Labels: approved, bot is merging ⏳

#1235 [17.0] copier repo update
  .copier-answers.yml
  .pre-commit-config.yaml
  .ruff.toml
  account_payment_purchase/models/purchase_order.py
Labels: bot is merging ⏳

#1221 [16.0][ADD] account_payment_method_fs_storage: init
  account_payment_method_fs_storage/README.rst
  account_payment_method_fs_storage/__init__.py
  account_payment_method_fs_storage/__manifest__.py
  account_payment_method_fs_storage/models/__init__.py
  account_payment_method_fs_storage/models/account_payment_method.py
  account_payment_method_fs_storage/models/account_payment_order.py
  account_payment_method_fs_storage/models/fs_storage.py
  account_payment_method_fs_storage/readme/CONFIGURE.rst
  account_payment_method_fs_storage/readme/CONTRIBUTORS.rst
  account_payment_method_fs_storage/readme/DESCRIPTION.rst
  account_payment_method_fs_storage/readme/INSTALL.rst
  account_payment_method_fs_storage/readme/USAGE.rst
  account_payment_method_fs_storage/static/description/icon.png
  account_payment_method_fs_storage/static/description/index.html
  account_payment_method_fs_storage/tests/__init__.py
  account_payment_method_fs_storage/tests/test_account_payment_method_fs_storage.py
  account_payment_method_fs_storage/views/account_payment_method.xml
  account_payment_method_fs_storage/views/fs_storage.xml
  setup/account_payment_method_fs_storage/odoo/addons/account_payment_method_fs_storage
  setup/account_payment_method_fs_storage/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1238 [16.0][ADD] account_banking_mandate_sale_contact: new module
  account_banking_mandate_sale_contact/README.rst
  account_banking_mandate_sale_contact/__init__.py
  account_banking_mandate_sale_contact/__manifest__.py
  account_banking_mandate_sale_contact/models/__init__.py
  account_banking_mandate_sale_contact/models/res_company.py
  account_banking_mandate_sale_contact/models/res_config_settings.py
  account_banking_mandate_sale_contact/models/res_partner.py
  account_banking_mandate_sale_contact/models/sale_order.py
  account_banking_mandate_sale_contact/readme/CONFIGURE.md
  account_banking_mandate_sale_contact/readme/CONTRIBUTORS.md
  account_banking_mandate_sale_contact/readme/DESCRIPTION.md
  account_banking_mandate_sale_contact/readme/USAGE.md
  account_banking_mandate_sale_contact/static/description/icon.png
  account_banking_mandate_sale_contact/static/description/index.html
  account_banking_mandate_sale_contact/tests/__init__.py
  account_banking_mandate_sale_contact/tests/test_account_banking_mandate_sale_contact.py
  account_banking_mandate_sale_contact/views/res_config_settings.xml
  account_banking_mandate_sale_contact/views/res_partner.xml
  setup/account_banking_mandate_sale_contact/odoo/addons/account_banking_mandate_sale_contact
  setup/account_banking_mandate_sale_contact/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1241 [16.0][FIX] account_banking_mandate_sale_contact: icon, readme, views
  account_banking_mandate_sale_contact/README.rst
  account_banking_mandate_sale_contact/__manifest__.py
  account_banking_mandate_sale_contact/readme/CONFIGURE.md
  account_banking_mandate_sale_contact/readme/CONTRIBUTORS.md
  account_banking_mandate_sale_contact/readme/USAGE.md
  account_banking_mandate_sale_contact/static/description/icon.png
  account_banking_mandate_sale_contact/static/description/icon.svg
  account_banking_mandate_sale_contact/static/description/index.html
  account_banking_mandate_sale_contact/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#1231 [17.0][MIG] account_banking_pain_base: Migration to 17.0
  account_banking_pain_base/README.rst
  account_banking_pain_base/__init__.py
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/i18n/account_banking_pain_base.pot
  account_banking_pain_base/i18n/ca.po
  account_banking_pain_base/i18n/de.po
  account_banking_pain_base/i18n/es.po
  account_banking_pain_base/i18n/es_AR.po
  account_banking_pain_base/i18n/fr.po
  account_banking_pain_base/i18n/hr.po
  account_banking_pain_base/i18n/it.po
  account_banking_pain_base/i18n/nb_NO.po
  account_banking_pain_base/i18n/nl.po
  account_banking_pain_base/i18n/pt_BR.po
  account_banking_pain_base/i18n/sl.po
  account_banking_pain_base/i18n/sv.po
  account_banking_pain_base/models/__init__.py
  account_banking_pain_base/models/account_payment_line.py
  account_banking_pain_base/models/account_payment_method.py
  account_banking_pain_base/models/account_payment_mode.py
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/models/res_bank.py
  account_banking_pain_base/models/res_company.py
  account_banking_pain_base/models/res_config_settings.py
  account_banking_pain_base/post_install.py
  account_banking_pain_base/pyproject.toml
  account_banking_pain_base/readme/CONFIGURE.md
  account_banking_pain_base/readme/CONTRIBUTORS.md
  account_banking_pain_base/readme/CREDITS.md
  account_banking_pain_base/readme/DESCRIPTION.md
  account_banking_pain_base/readme/INSTALL.md
  account_banking_pain_base/readme/USAGE.md
  account_banking_pain_base/security/security.xml
  account_banking_pain_base/static/description/icon.png
  account_banking_pain_base/static/description/index.html
  account_banking_pain_base/views/account_payment_line.xml
  account_banking_pain_base/views/account_payment_method.xml
  account_banking_pain_base/views/account_payment_mode.xml
  account_banking_pain_base/views/account_payment_order.xml
  account_banking_pain_base/views/res_config_settings.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#1236 [17.0][MIG] account_banking_sepa_credit_transfer: Migration to 17.0
  account_banking_sepa_credit_transfer/README.rst
  account_banking_sepa_credit_transfer/__init__.py
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/data/account_payment_method.xml
  account_banking_sepa_credit_transfer/data/pain.001.001.02.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.03.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.04.xsd
  account_banking_sepa_credit_transfer/data/pain.001.001.05.xsd
  account_banking_sepa_credit_transfer/data/pain.001.003.03.xsd
  account_banking_sepa_credit_transfer/demo/sepa_credit_transfer_demo.xml
  account_banking_sepa_credit_transfer/i18n/account_banking_sepa_credit_transfer.pot
  account_banking_sepa_credit_transfer/i18n/ca.po
  account_banking_sepa_credit_transfer/i18n/de.po
  account_banking_sepa_credit_transfer/i18n/es.po
  account_banking_sepa_credit_transfer/i18n/es_AR.po
  account_banking_sepa_credit_transfer/i18n/fr.po
  account_banking_sepa_credit_transfer/i18n/fr_FR.po
  account_banking_sepa_credit_transfer/i18n/hr.po
  account_banking_sepa_credit_transfer/i18n/nb_NO.po
  account_banking_sepa_credit_transfer/i18n/nl.po
  account_banking_sepa_credit_transfer/i18n/pt_BR.po
  account_banking_sepa_credit_transfer/i18n/sl.po
  account_banking_sepa_credit_transfer/i18n/sv.po
  account_banking_sepa_credit_transfer/models/__init__.py
  account_banking_sepa_credit_transfer/models/account_payment_line.py
  account_banking_sepa_credit_transfer/models/account_payment_method.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/pyproject.toml
  account_banking_sepa_credit_transfer/readme/CONFIGURE.md
  account_banking_sepa_credit_transfer/readme/CONTRIBUTORS.md
  account_banking_sepa_credit_transfer/readme/CREDITS.md
  account_banking_sepa_credit_transfer/readme/DESCRIPTION.md
  account_banking_sepa_credit_transfer/readme/INSTALL.md
  account_banking_sepa_credit_transfer/readme/USAGE.md
  account_banking_sepa_credit_transfer/static/description/icon.png
  account_banking_sepa_credit_transfer/static/description/icon.svg
  account_banking_sepa_credit_transfer/static/description/index.html
  account_banking_sepa_credit_transfer/tests/__init__.py
  account_banking_sepa_credit_transfer/tests/test_sct.py
Labels: approved, ready to merge, bot is merging ⏳

#1180 [15.0][IMP] account_banking_sepa_direct_debit: Button send mandate per email
  account_banking_sepa_direct_debit/README.rst
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/data/mail_template_data.xml
  account_banking_sepa_direct_debit/i18n/account_banking_sepa_direct_debit.pot
  account_banking_sepa_direct_debit/i18n/es.po
  account_banking_sepa_direct_debit/models/__init__.py
  account_banking_sepa_direct_debit/models/account_banking_mandate.py
  account_banking_sepa_direct_debit/models/mail_compose_message.py
  account_banking_sepa_direct_debit/readme/CONTRIBUTORS.rst
  account_banking_sepa_direct_debit/static/description/index.html
  account_banking_sepa_direct_debit/tests/test_mandate.py
  account_banking_sepa_direct_debit/views/account_banking_mandate_view.xml
Labels: approved, ready to merge, bot is merging ⏳
