Repository OCA/bank-payment, pull requests merged in 2025-04, with the labels that each got.

#1441 [17.0][FIX] account_payment_order: Fix chatter HTML link formatting on invoice payment
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/am.po
  account_payment_order/i18n/ar.po
  account_payment_order/i18n/ca.po
  account_payment_order/i18n/ca_ES.po
  account_payment_order/i18n/cs.po
  account_payment_order/i18n/da_DK.po
  account_payment_order/i18n/de.po
  account_payment_order/i18n/el_GR.po
  account_payment_order/i18n/es.po
  account_payment_order/i18n/es_AR.po
  account_payment_order/i18n/es_CL.po
  account_payment_order/i18n/es_CR.po
  account_payment_order/i18n/es_EC.po
  account_payment_order/i18n/es_ES.po
  account_payment_order/i18n/es_MX.po
  account_payment_order/i18n/es_VE.po
  account_payment_order/i18n/et.po
  account_payment_order/i18n/fi.po
  account_payment_order/i18n/fr.po
  account_payment_order/i18n/fr_FR.po
  account_payment_order/i18n/gl.po
  account_payment_order/i18n/hr.po
  account_payment_order/i18n/it.po
  account_payment_order/i18n/lt.po
  account_payment_order/i18n/nb_NO.po
  account_payment_order/i18n/nl.po
  account_payment_order/i18n/nl_BE.po
  account_payment_order/i18n/nl_NL.po
  account_payment_order/i18n/pl.po
  account_payment_order/i18n/pt.po
  account_payment_order/i18n/pt_BR.po
  account_payment_order/i18n/pt_PT.po
  account_payment_order/i18n/ro.po
  account_payment_order/i18n/ru.po
  account_payment_order/i18n/sl.po
  account_payment_order/i18n/sv.po
  account_payment_order/i18n/th.po
  account_payment_order/i18n/tr.po
  account_payment_order/i18n/vi.po
  account_payment_order/models/account_move.py
Labels: bot is merging ⏳

#1374 [18.0][MIG] account_invoice_select_for_payment: Migration to 18.0
  account_invoice_select_for_payment/README.rst
  account_invoice_select_for_payment/__init__.py
  account_invoice_select_for_payment/__manifest__.py
  account_invoice_select_for_payment/i18n/account_invoice_select_for_payment.pot
  account_invoice_select_for_payment/i18n/es.po
  account_invoice_select_for_payment/i18n/it.po
  account_invoice_select_for_payment/i18n/sv.po
  account_invoice_select_for_payment/models/__init__.py
  account_invoice_select_for_payment/models/account_move.py
  account_invoice_select_for_payment/pyproject.toml
  account_invoice_select_for_payment/readme/CONTRIBUTORS.md
  account_invoice_select_for_payment/readme/CREDITS.md
  account_invoice_select_for_payment/readme/DESCRIPTION.md
  account_invoice_select_for_payment/readme/USAGE.md
  account_invoice_select_for_payment/static/description/icon.png
  account_invoice_select_for_payment/static/description/index.html
  account_invoice_select_for_payment/tests/__init__.py
  account_invoice_select_for_payment/tests/test_account_invoice_select_for_payment.py
  account_invoice_select_for_payment/views/account_move.xml
Labels: approved, ready to merge, merged 🎉

#1445 [17.0][IMP] account_payment_mode: change type of payment_mode.note field from Text to Html
  account_payment_mode/models/account_payment_mode.py
Labels: approved, bot is merging ⏳

#1385 [17.0][FIX] account_payment_order: Bugfix in TreeView of account.payment.line (invisible vs column_invisible)
  account_payment_order/views/account_payment_line.xml
Labels: bot is merging ⏳, stale

#1438 [18.0][MIG] account_payment_mode: Migration to version 18.0
  account_payment_mode/README.rst
  account_payment_mode/__init__.py
  account_payment_mode/__manifest__.py
  account_payment_mode/demo/payment_demo.xml
  account_payment_mode/i18n/account_payment_mode.pot
  account_payment_mode/i18n/am.po
  account_payment_mode/i18n/ca.po
  account_payment_mode/i18n/da_DK.po
  account_payment_mode/i18n/de.po
  account_payment_mode/i18n/el_GR.po
  account_payment_mode/i18n/es.po
  account_payment_mode/i18n/es_AR.po
  account_payment_mode/i18n/es_CL.po
  account_payment_mode/i18n/es_ES.po
  account_payment_mode/i18n/fi.po
  account_payment_mode/i18n/fr.po
  account_payment_mode/i18n/fr_FR.po
  account_payment_mode/i18n/gl.po
  account_payment_mode/i18n/hr.po
  account_payment_mode/i18n/it.po
  account_payment_mode/i18n/nb_NO.po
  account_payment_mode/i18n/nl.po
  account_payment_mode/i18n/pt.po
  account_payment_mode/i18n/pt_BR.po
  account_payment_mode/i18n/pt_PT.po
  account_payment_mode/i18n/sl.po
  account_payment_mode/i18n/sv.po
  account_payment_mode/i18n/sv_SE.po
  account_payment_mode/i18n/tr.po
  account_payment_mode/i18n/zh_CN.po
  account_payment_mode/migrations/18.0.1.0.0/noupdate_changes.xml
  account_payment_mode/migrations/18.0.1.0.0/post-migration.py
  account_payment_mode/models/__init__.py
  account_payment_mode/models/account_journal.py
  account_payment_mode/models/account_payment_method.py
  account_payment_mode/models/account_payment_mode.py
  account_payment_mode/pyproject.toml
  account_payment_mode/readme/CONFIGURE.md
  account_payment_mode/readme/CONTRIBUTORS.md
  account_payment_mode/readme/DESCRIPTION.md
  account_payment_mode/readme/USAGE.md
  account_payment_mode/security/account_payment_mode.xml
  account_payment_mode/security/ir.model.access.csv
  account_payment_mode/static/description/icon.png
  account_payment_mode/static/description/index.html
  account_payment_mode/tests/__init__.py
  account_payment_mode/tests/test_account_payment_mode.py
  account_payment_mode/views/account_journal.xml
  account_payment_mode/views/account_payment_method.xml
  account_payment_mode/views/account_payment_mode.xml
Labels: approved, ready to merge, bot is merging ⏳

#1439 [18.0][MIG] account_payment_partner: Migration to version 18.0
  account_payment_partner/README.rst
  account_payment_partner/__init__.py
  account_payment_partner/__manifest__.py
  account_payment_partner/demo/partner_demo.xml
  account_payment_partner/hooks.py
  account_payment_partner/i18n/account_payment_partner.pot
  account_payment_partner/i18n/ca.po
  account_payment_partner/i18n/da_DK.po
  account_payment_partner/i18n/de.po
  account_payment_partner/i18n/es.po
  account_payment_partner/i18n/es_AR.po
  account_payment_partner/i18n/es_CL.po
  account_payment_partner/i18n/fr.po
  account_payment_partner/i18n/fr_FR.po
  account_payment_partner/i18n/hr.po
  account_payment_partner/i18n/it.po
  account_payment_partner/i18n/nb_NO.po
  account_payment_partner/i18n/nl.po
  account_payment_partner/i18n/pt.po
  account_payment_partner/i18n/pt_BR.po
  account_payment_partner/i18n/sl.po
  account_payment_partner/i18n/sv.po
  account_payment_partner/models/__init__.py
  account_payment_partner/models/account_move.py
  account_payment_partner/models/account_move_line.py
  account_payment_partner/models/account_payment_mode.py
  account_payment_partner/models/res_partner.py
  account_payment_partner/pyproject.toml
  account_payment_partner/readme/CONTRIBUTORS.md
  account_payment_partner/readme/DESCRIPTION.md
  account_payment_partner/readme/HISTORY.md
  account_payment_partner/readme/USAGE.md
  account_payment_partner/reports/__init__.py
  account_payment_partner/reports/account_invoice_report.py
  account_payment_partner/reports/account_invoice_report_view.xml
  account_payment_partner/security/account_payment_partner_security.xml
  account_payment_partner/static/description/icon.png
  account_payment_partner/static/description/index.html
  account_payment_partner/tests/__init__.py
  account_payment_partner/tests/test_account_payment_partner.py
  account_payment_partner/views/account_move_line.xml
  account_payment_partner/views/account_move_view.xml
  account_payment_partner/views/account_payment_mode.xml
  account_payment_partner/views/report_invoice.xml
  account_payment_partner/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1450 [18.0][MIG] account_banking_mandate_contact: Migration to 18.0
  account_banking_mandate_contact/README.rst
  account_banking_mandate_contact/__init__.py
  account_banking_mandate_contact/__manifest__.py
  account_banking_mandate_contact/i18n/account_banking_mandate_contact.pot
  account_banking_mandate_contact/i18n/es.po
  account_banking_mandate_contact/i18n/it.po
  account_banking_mandate_contact/models/__init__.py
  account_banking_mandate_contact/models/account_move_line.py
  account_banking_mandate_contact/models/res_partner.py
  account_banking_mandate_contact/pyproject.toml
  account_banking_mandate_contact/readme/CONTRIBUTORS.md
  account_banking_mandate_contact/readme/DESCRIPTION.md
  account_banking_mandate_contact/readme/USAGE.md
  account_banking_mandate_contact/static/description/icon.png
  account_banking_mandate_contact/static/description/index.html
  account_banking_mandate_contact/tests/__init__.py
  account_banking_mandate_contact/tests/test_account_payment_order.py
  account_banking_mandate_contact/views/res_partner.xml
Labels: approved, bot is merging ⏳

#1448 [18.0][FIX] account_banking_mandate: fix mandates button display in partner view
  account_banking_mandate/views/res_partner.xml
Labels: approved, bot is merging ⏳

#1442 [16.0][FIX] account_banking_pain_base : fix DbtrAcct node
  account_banking_pain_base/models/account_payment_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1454 [18.0][FIX] account_payment_partner: fix column_invisible in list view view_move_line_tree
  account_payment_partner/views/account_move_line.xml
Labels: approved, bot is merging ⏳

#1451 [18.0][MIG] account_payment_purchase_stock
  account_payment_purchase_stock/README.rst
  account_payment_purchase_stock/__init__.py
  account_payment_purchase_stock/__manifest__.py
  account_payment_purchase_stock/i18n/account_payment_purchase_stock.pot
  account_payment_purchase_stock/i18n/ca.po
  account_payment_purchase_stock/i18n/es.po
  account_payment_purchase_stock/i18n/es_AR.po
  account_payment_purchase_stock/i18n/fr.po
  account_payment_purchase_stock/i18n/fr_FR.po
  account_payment_purchase_stock/i18n/it.po
  account_payment_purchase_stock/models/__init__.py
  account_payment_purchase_stock/models/stock_rule.py
  account_payment_purchase_stock/pyproject.toml
  account_payment_purchase_stock/readme/CONTRIBUTORS.md
  account_payment_purchase_stock/readme/DESCRIPTION.md
  account_payment_purchase_stock/readme/INSTALL.md
  account_payment_purchase_stock/readme/USAGE.md
  account_payment_purchase_stock/static/description/icon.png
  account_payment_purchase_stock/static/description/index.html
  account_payment_purchase_stock/tests/__init__.py
  account_payment_purchase_stock/tests/test_account_payment_purchase_stock.py
Labels: approved, ready to merge, bot is merging ⏳
